import { TICKET_CONVERSATIONS_TYPE } from '@/constants/strings';

export const TICKET_CONVERSATION_ACTIONS = {
  [TICKET_CONVERSATIONS_TYPE?.NOTE]: 'notified to',
  [TICKET_CONVERSATIONS_TYPE?.REPLY]: 'replied to',
  [TICKET_CONVERSATIONS_TYPE?.FORWARD]: 'forwarded to',
};

export const TICKET_CONVERSATION_PORTAL_ACTIONS_CONSTANT = {
  ADD_NOTE: 'add Note',
  EDIT_NOTE: 'edit Note',
  DELETE_NOTE: 'delete Note',
  REPLY: 'Reply',
  FORWARD: 'Forward',
  DISCUSS: 'discuss',
};

export const TICKET_CONVERSATION_RESPONSE_PORTAL_ACTIONS_CONSTANT = {
  CANNED_RESPONSE: 'CANNED RESPONSES',
  ARTICLE_REPONSE: 'ARTICLE RESPONSES',
};
