import { FEEDBACK_SURVEY_QUESTION_RESPONSE_GRADE } from '@/constants/strings';

export const progressBarColors: any = {
  [FEEDBACK_SURVEY_QUESTION_RESPONSE_GRADE?.EXCELLENT]: 'success.main',
  [FEEDBACK_SURVEY_QUESTION_RESPONSE_GRADE?.VERY_GOOD]: 'warning.main',
  [FEEDBACK_SURVEY_QUESTION_RESPONSE_GRADE?.GOOD]: 'error.main',
  [FEEDBACK_SURVEY_QUESTION_RESPONSE_GRADE?.SATISFIED]: 'info.main',
  [FEEDBACK_SURVEY_QUESTION_RESPONSE_GRADE?.UN_SATISFIED]: 'primary.main',
};
