export const superAdminTabsData = [
  'All',
  'User Management',
  'Plan Management',
  'Billing invoices',
  'Reports',
  'FAQs',
  'Enquiries',
  'Tax Calculation',
  'Quick Links',
  'News and Events',
  'Modules Creation',
  'product Features',
];

export const orgAdminTabsData = [
  'All',
  'Users',
  'Organizations',
  'Subscription Invoices',
  'Properties',
  'Role and Rights',
  'sales product categories',
  'Life Cycle Stage',
  'Contact Status',
  'Receiver Bank Account',
  'Calls',
  'Contacts',
  'Meetings',
  'Documents',
  'Chats',
  'Emails',
  'Companies',
];

export const airSalesTabsData = [
  'All',
  'Deals',
  'Forecast',
  'Quotes',
  'Tasks',
  'Invoices',
  'Reports',
  'Settings',
  'Calls',
  'Contacts',
  'Meetings',
  'Documents',
  'Chats',
  'Emails',
  'Companies',
];

export const airServicesTabsData = [
  'All',
  'Tickets',
  'Inventorys',
  'Softwares',
  'Contracts',
  'Purchase Orders',
  'knowledge base',
  'WorkLoads',
  // 'Feedback Survey',
  'Ffedback Surways',
  'Reports',
  // 'Enquiries',
  'Enquireies',
  'Signup Leads',
  'Account Settings',
  'User Management',
  'Asset Management',
  'Agent Productivity Workload Management',
  'Service Management',
  'Calls',
  'Contacts',
  'Meetings',
  'Documents',
  'Chats',
  'Emails',
  'Companies',
];

export const airOperationsTabsData = [
  'All',
  'Data Management',
  'Workflow Automation',
  'Reports',
  'Roles Right',
  'User Management',
  'Calls',
  'Contacts',
  'Meetings',
  'Documents',
  'Chats',
  'Emails',
  'Companies',
];

export const subModulesSetting = [
  'AGENTS',
  'DEPARTMENTS',
  'REQUESTERS',
  'AGENT_REQUESTERS',
  'ROLES_AND_RIGHTS',
  'ASSET_TYPES',
  'PRODUCT_CATALOGS',
  'VENDORS',
  'WORKLOADS',
  'CANNED_RESPONSES',
  'INVENTORYS',
  'SOFTWARES',
  'CONTRACTS',
  'PURCHAHSE_ORDERS',
  'BUSINESS_HOURS',
  'CATALOGS',
  'KNOWLEDGE_BASE',
];
export const subModulesAirOperationData = ['DEALS', 'QUOTES', 'TASKS'];
