export const data = [
  {
    id: '001',
    status: 'active',
    product: 'Sales',
    price: '20',
    numberOfUsers: '3',
    planDuration: 'Paid Monthly',
    planUsers: '2',
    planData: '3GB',
    billOn: '20th Feb 2024',
    type: 'Growth Plan',
  },
  {
    id: '002',
    status: 'inactive',
    product: 'Service',
    price: '0',
    numberOfUsers: '1',
    planDuration: '',
    planUsers: '1',
    planData: '3GB',
    billOn: '-',
    type: 'Free Plan',
  },
  {
    id: '003',
    status: 'inactive',
    product: 'Marketing',
    price: '0',
    numberOfUsers: '1',
    planDuration: '',
    planUsers: '1',
    planData: '3GB',
    billOn: '-',
    type: 'Free Plan',
  },
  {
    id: '004',
    status: 'active',
    product: 'Operation',
    price: '20',
    numberOfUsers: '1',
    planDuration: 'Paid Monthly',
    planUsers: '1',
    planData: '5GB',
    billOn: '20th Feb 2024',
    type: 'Growth Plan',
  },
  {
    id: '005',
    status: 'inactive',
    product: 'Loyalty Program',
    price: '0',
    numberOfUsers: '1',
    planDuration: 'Paid Monthly',
    planUsers: '1',
    planData: '5GB',
    billOn: '-',
    type: 'Free Plan',
  },
];
