import {
  DYNAMIC_REPORTS_TYPES,
  GENERIC_REPORT_MODULES,
} from '@/constants/strings';
import {
  AIR_OPERATION_REPORTS_SALES_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_FAVOURITES_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_FAVOURITES_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_FAVOURITES_PERMISSIONS,
} from '@/constants/permission-keys';

const { SERVICES, SALES, MARKETING } = GENERIC_REPORT_MODULES ?? {};

export const TAB_CHANGED_FILTERED: any = {
  0: [],
  1: [['isFavorite', true + '']],
  2: [['type', DYNAMIC_REPORTS_TYPES?.DASHBOARD]],
  3: [['type', DYNAMIC_REPORTS_TYPES?.CUSTOM]],
};

export const PERMISSIONS_REPORTS = {
  [`${SERVICES}0`]: AIR_OPERATION_REPORTS_SERVICES_ALL_REPORTS_PERMISSIONS,
  [`${SERVICES}1`]: AIR_OPERATION_REPORTS_SERVICES_FAVOURITES_PERMISSIONS,
  [`${SERVICES}2`]:
    AIR_OPERATION_REPORTS_SERVICES_DASHBOARD_REPORTS_PERMISSIONS,
  [`${SERVICES}3`]: AIR_OPERATION_REPORTS_SERVICES_CUSTOM_REPORTS_PERMISSIONS,
  [`${SALES}0`]: AIR_OPERATION_REPORTS_SALES_ALL_REPORTS_PERMISSIONS,
  [`${SALES}1`]: AIR_OPERATION_REPORTS_SALES_FAVOURITES_PERMISSIONS,
  [`${SALES}2`]: AIR_OPERATION_REPORTS_SALES_DASHBOARD_REPORTS_PERMISSIONS,
  [`${SALES}3`]: AIR_OPERATION_REPORTS_SALES_CUSTOM_REPORTS_PERMISSIONS,
  [`${MARKETING}0`]: AIR_OPERATION_REPORTS_MARKETING_ALL_REPORTS_PERMISSIONS,
  [`${MARKETING}1`]: AIR_OPERATION_REPORTS_MARKETING_FAVOURITES_PERMISSIONS,
  [`${MARKETING}2`]:
    AIR_OPERATION_REPORTS_MARKETING_DASHBOARD_REPORTS_PERMISSIONS,
  [`${MARKETING}3`]: AIR_OPERATION_REPORTS_MARKETING_CUSTOM_REPORTS_PERMISSIONS,
};
