import {
  DYNAMIC_REPORTS_TYPES,
  GENERIC_REPORT_MODULES,
} from '@/constants/strings';
import { AIR_OPERATIONS } from '@/constants';
import {
  AIR_OPERATION_REPORTS_SALES_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_FAVOURITES_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_FAVOURITES_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_FAVOURITES_PERMISSIONS,
} from '@/constants/permission-keys';

const { SERVICES, SALES, MARKETING } = GENERIC_REPORT_MODULES;

const { SALES_REPORTS, SERVICES_REPORTS, MARKETING_REPORTS } = AIR_OPERATIONS;

export const REPORTS_BASE_MODULE: any = {
  [SERVICES_REPORTS]: SERVICES,
  [SALES_REPORTS]: SALES,
  [MARKETING_REPORTS]: MARKETING,
};

export const TAB_CHANGED_FILTERED: any = {
  0: [],
  1: [['isFavorite', true + '']],
  2: [['type', DYNAMIC_REPORTS_TYPES?.DASHBOARD]],
  3: [['type', DYNAMIC_REPORTS_TYPES?.CUSTOM]],
};

export const PERMISSIONS_REPORTS = {
  [`${SERVICES_REPORTS}0`]:
    AIR_OPERATION_REPORTS_SERVICES_ALL_REPORTS_PERMISSIONS,
  [`${SERVICES_REPORTS}1`]:
    AIR_OPERATION_REPORTS_SERVICES_FAVOURITES_PERMISSIONS,
  [`${SERVICES_REPORTS}2`]:
    AIR_OPERATION_REPORTS_SERVICES_DASHBOARD_REPORTS_PERMISSIONS,
  [`${SERVICES_REPORTS}3`]:
    AIR_OPERATION_REPORTS_SERVICES_CUSTOM_REPORTS_PERMISSIONS,
  [`${SALES_REPORTS}0`]: AIR_OPERATION_REPORTS_SALES_ALL_REPORTS_PERMISSIONS,
  [`${SALES_REPORTS}1`]: AIR_OPERATION_REPORTS_SALES_FAVOURITES_PERMISSIONS,
  [`${SALES_REPORTS}2`]:
    AIR_OPERATION_REPORTS_SALES_DASHBOARD_REPORTS_PERMISSIONS,
  [`${SALES_REPORTS}3`]: AIR_OPERATION_REPORTS_SALES_CUSTOM_REPORTS_PERMISSIONS,
  [`${MARKETING_REPORTS}0`]:
    AIR_OPERATION_REPORTS_MARKETING_ALL_REPORTS_PERMISSIONS,
  [`${MARKETING_REPORTS}1`]:
    AIR_OPERATION_REPORTS_MARKETING_FAVOURITES_PERMISSIONS,
  [`${MARKETING_REPORTS}2`]:
    AIR_OPERATION_REPORTS_MARKETING_DASHBOARD_REPORTS_PERMISSIONS,
  [`${MARKETING_REPORTS}3`]:
    AIR_OPERATION_REPORTS_MARKETING_CUSTOM_REPORTS_PERMISSIONS,
};
