version: '3'
services:
  aac-fe:
    container_name: aac-fe
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"