import {
  BarChart,
  DonutChart,
  HorizontalChart,
  PieChart,
  Table,
  TemplateText,
  Text,
} from '@/components/DynamicWidgets';

export const REPORTS_WIDGETS = {
  BAR_CHART: 'BAR_CHART',
  HORIZONTAL_BAR_CHART: 'HORIZONTAL_BAR_CHART',
  DONUT_CHART: 'DONUT_CHART',
  PIE_CHART: 'PIE_CHART',
  TEMPLATE_BAR_CHART: 'TEMPLATE_BAR_CHART',
  TEMPLATE_PIE_OR_DONUT_CHART: 'TEMPLATE_PIE_OR_DONUT_CHART',
  TABLE: 'TABLE',
  TEXT_FIELD: 'TEXT_FIELD',
  TEMPLATE_TABLE: 'TEMPLATE_TABLE',
  TEMPLATE_TEXT: 'TEMPLATE_TEXT',
  TEMPLATE_PIE_CHART: 'TEMPLATE_PIE_CHART',
  TEMPLATE_DONUT_CHART: 'TEMPLATE_DONUT_CHART',
  TEMPLATE_HORIZONTAL_BAR_CHART: 'TEMPLATE_HORIZONTAL_BAR_CHART',
};

export const REPORTS_WIDGET_COMPONENT: any = {
  [REPORTS_WIDGETS?.BAR_CHART]: BarChart,
  [REPORTS_WIDGETS?.DONUT_CHART]: DonutChart,
  [REPORTS_WIDGETS?.HORIZONTAL_BAR_CHART]: HorizontalChart,
  [REPORTS_WIDGETS?.PIE_CHART]: PieChart,
  [REPORTS_WIDGETS?.TABLE]: Table,
  [REPORTS_WIDGETS?.TEMPLATE_BAR_CHART]: BarChart,
  [REPORTS_WIDGETS?.TEMPLATE_PIE_OR_DONUT_CHART]: PieChart,
  [REPORTS_WIDGETS?.TEXT_FIELD]: Text,
  [REPORTS_WIDGETS?.TEMPLATE_TABLE]: Table,
  [REPORTS_WIDGETS?.TEMPLATE_TEXT]: TemplateText,
  [REPORTS_WIDGETS?.TEMPLATE_PIE_CHART]: PieChart,
  [REPORTS_WIDGETS?.TEMPLATE_DONUT_CHART]: DonutChart,
  [REPORTS_WIDGETS?.TEMPLATE_HORIZONTAL_BAR_CHART]: HorizontalChart,
};
