import Link from 'next/link';

import {
  Box,
  Button,
  Card,
  CardContent,
  Grid,
  Typography,
  useTheme,
} from '@mui/material';
import { ArrowBack } from '@mui/icons-material';

import Search from '@/components/Search';
import TanstackTable from '@/components/Table/TanstackTable';
import SwitchableDatepicker from '@/components/SwitchableDatepicker';
import { usersData, usersColumns, CTAReport } from './reports.data';
import InvoicesAnalystGraph from './InvoicesAnalystGraph';
import useMarketerReports from './useMarketerReports';

import { DownloadIcon } from '@/assets/icons';

import { v4 as uuidv4 } from 'uuid';
import { AIR_MARKETER } from '@/routesConstants/paths';

const LeadaReports = () => {
  const theme = useTheme();
  const { searchBy, setSearchBy }: any = useMarketerReports();

  return (
    <Box>
      <Box
        display="flex"
        alignItems="center"
        justifyContent="space-between"
        flexWrap="wrap"
        gap={1}
        mb={2}
      >
        <Box
          sx={{
            display: 'flex',
            alignItems: 'center',
          }}
        >
          <Link href={AIR_MARKETER?.REPORTS}>
            <ArrowBack sx={{ mt: 1 }} />
          </Link>
          <Typography
            variant="h3"
            sx={{ color: theme?.palette?.slateBlue['main'] }}
          >
            Leads CTAs
          </Typography>
        </Box>
        <Box display="flex" flexWrap="wrap" alignItems="center" gap={1}>
          <SwitchableDatepicker placement="right" renderInput={'button'} />
          <Button
            sx={{ p: 0 }}
            className="small"
            variant="outlined"
            color="inherit"
          >
            <DownloadIcon />
          </Button>
        </Box>
      </Box>
      <Box>
        <Typography
          variant="h5"
          sx={{
            fontWeight: 400,
            color: theme?.palette?.blue?.light,
          }}
        >
          Total Leads Generated by CTAs
          <Typography
            variant="subtitle1"
            sx={{
              color: theme?.palette?.primary['main'],
              ml: 1,
            }}
            component="span"
          >
            10
          </Typography>
        </Typography>
      </Box>
      <Typography
        sx={{ color: theme?.palette?.slateBlue['main'], my: 2 }}
        variant="h5"
      >
        CTA Report
      </Typography>

      <Grid container spacing={2}>
        {CTAReport?.map((item: any) => {
          return (
            <Grid item lg={3} md={4} sm={6} xs={12} key={uuidv4()}>
              <Card
                sx={{
                  height: '98px',
                  border: `1px solid ${theme?.palette?.custom?.hawkes_blue}`,
                  mb: 1,
                }}
              >
                <CardContent
                  sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    p: '16px',
                    alignItems: 'center',
                  }}
                >
                  <Typography
                    sx={{ color: theme?.palette?.custom?.steel_blue_alpha }}
                    variant="h6"
                    gutterBottom
                  >
                    {item?.reportView}
                  </Typography>
                  <Typography
                    variant="h3"
                    sx={{
                      color: theme?.palette?.custom?.turquoise_Blue,
                      mb: 1.5,
                    }}
                  >
                    {item?.Values}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          );
        })}
      </Grid>

      <Card sx={{ mb: '10px' }}>
        <InvoicesAnalystGraph />
      </Card>
      <Card>
        <Box
          display="flex"
          justifyContent="space-between"
          alignItems="center"
          mx={2}
          my={1}
        >
          <Search
            label="Search Here"
            searchBy={searchBy}
            setSearchBy={setSearchBy}
            width={240}
          />
        </Box>
        <Box>
          <TanstackTable
            columns={usersColumns}
            data={usersData()}
            isPagination
            count={10}
            totalRecords={10}
            setPageLimit={10}
          />
        </Box>
      </Card>
    </Box>
  );
};

export default LeadaReports;
