import Link from 'next/link';

import {
  Box,
  Button,
  Card,
  CardContent,
  Grid,
  Typography,
  useTheme,
} from '@mui/material';
import { ArrowBack } from '@mui/icons-material';

import Search from '@/components/Search';
import TanstackTable from '@/components/Table/TanstackTable';
import CustomPagination from '@/components/CustomPagination';
import SwitchableDatepicker from '@/components/SwitchableDatepicker';
import { usersData, usersColumns, CTAReport } from './reports.data';
import InvoicesAnalystGraph from './InvoicesAnalystGraph';
import useMarketerReports from './useMarketerReports';

import { DownloadIcon } from '@/assets/icons';

import { v4 as uuidv4 } from 'uuid';

const LeadaReports = () => {
  const theme = useTheme();
  const { searchBy, setSearchBy }: any = useMarketerReports();

  return (
    <Box>
      <Box display="flex" alignItems="center" gap={1} mb={2}>
        <Box mt={1}>
          <Link href="/air-marketer/reports">
            <ArrowBack />
          </Link>
        </Box>
        <Box width="100%" display="flex" justifyContent="space-between">
          <Typography variant="h3" sx={{ color: '#374151' }}>
            Leads CTAs
          </Typography>
          <SwitchableDatepicker />
        </Box>
        <Button
          sx={{ p: 0 }}
          className="small"
          variant="outlined"
          color="inherit"
        >
          <DownloadIcon />
        </Button>
      </Box>
      <Box>
        <Typography
          variant="h3"
          sx={{
            fontSize: '18px',
            fontWeight: 400,
            color: theme?.palette?.blue['main'],
          }}
        >
          Total Leads Generated by CTAs
          <Typography
            variant="h3"
            sx={{
              fontSize: '20px',
              fontWeight: 700,
              color: theme?.palette?.primary['main'],
              ml: 1,
            }}
            component="span"
          >
            10
          </Typography>
        </Typography>
      </Box>
      <Typography
        sx={{ color: theme?.palette?.slateBlue['main'], my: 2 }}
        variant="h5"
      >
        CTA Report
      </Typography>

      <Grid container spacing={1}>
        {CTAReport?.map((item: any) => {
          return (
            <Grid item lg={3} md={4} sm={6} xs={12} key={uuidv4()}>
              <Card sx={{ height: '98px', border: '1px solid #D2D6DF', mb: 1 }}>
                <CardContent
                  sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    p: '16px',
                    alignItems: 'center',
                  }}
                >
                  <Typography
                    sx={{ fontSize: 16, color: '#79839E', fontWeight: 500 }}
                    color="text.secondary"
                    gutterBottom
                  >
                    {item?.reportView}
                  </Typography>
                  <Typography
                    sx={{
                      mb: 1.5,
                      fontSize: 24,
                      color: '#4CCFBC',
                      fontWeight: 600,
                    }}
                    color="text.secondary"
                  >
                    {item?.Values}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          );
        })}
      </Grid>

      <Card sx={{ mb: '10px' }}>
        <InvoicesAnalystGraph />
      </Card>
      <Card>
        <Box
          display="flex"
          justifyContent="space-between"
          alignItems="center"
          mx={2}
          my={1}
        >
          <Search
            label="Search Here"
            searchBy={searchBy}
            setSearchBy={setSearchBy}
            width={240}
          />
        </Box>
        <Box>
          <TanstackTable columns={usersColumns} data={usersData} />
          <CustomPagination
            count={1}
            rowsPerPageOptions={[1, 2]}
            entriePages={1}
          />
        </Box>
      </Card>
    </Box>
  );
};

export default LeadaReports;
