export const END_POINTS = {
  LOGIN: 'auth/signin',
  SIGNUP: 'auth/signup',
  verify_token: 'auth/verify-token',
  search_company: 'auth/signup',
  get_permissions: '/premissions',
  reset_password: 'auth/resetPassword',
  FORGOT_PASSWORD: 'auth/forgot-password',
  INVENTORY_ACTIVITY: 'assets/inventory',
  WORKLOAD: `/workload/workload-management`,
  INVENTORY_EXPENSE: '/expense/add-expense',
  GET_INVENTORY_EXPENSE: '/expense/get-expense',
  SUPER_ADMIN_ROLES: '/permissions/super-admin-roles',
  TICKET: '/ticket',
  TICKET_TIME_ENTRIES: '/ticket/add-time-entries',
  TICKET_UPDATE_TIME_ENTRIES: '/ticket/update-time-entries',
  TICKET_TIME_LIST: '/ticket/get-time-entries',
  TICKET_STATUS: '/ticket/status',
  TICKET_BULK_UPDATE: '/ticket/bulk-ticket-update',
  USER_LIST: '/users',
  ADD_USER: '/users',
  USER_AVATAR: 'avatar',
  ORG_ADMIN_EMP_LIST: '/users/organization',
  ORGANIZATION: '/organization',
  USER_ACCOUNTS_LIST: '/super-admin/accounts-list',
  USER_ACCOUNT: '/account',
  UPDATE_USER_LIST: '/users/edit',
  ADD_ACCOUNTS: '/super-admin/add-accounts',
  COMPANY_CRN: '/auth/search-company',
  auth_search_company: 'auth/search-company',
  DEALS_LIST_VIEW: '/deals/get-deals-list-view',
  POST_DEALS: '/deals',
  DEALS_REPORTS: '/deals/deal-report',
  SUPER_ADMIN_USERS_REPORTS: '/super-admin/user-product-wise-stats',
  SUPER_ADMIN_INVOICES_REPORTS: '/super-admin/get-invoice-report',
  DEALS_PIPELINE: '/deal-pipeline',
  DEALS_LIFECYCLE_STAGES: '/lifecycle-stages',
  DEALS_USER_LIST: '/super-admin/user-list',
  DEALS_GRID_VIEW: '/deals/get-deals-grid-view',
  DEALS_CUSTOMIZE_COLUMN: '/customized-columns',
  DEALS_ACTION_PREVIEW: '/deals/deal-action-preview/{id}',
  POST_DEALS_VIEW: '/deal-views',
  GET_DEALS_VIEWS: '/deal-views',
  DELETE_DEALS: '/deals/delete-deals',
  RESTORE_DEALS: '/deals/get-soft-deleted-deals',
  EMAIL_EXIST: '/users/email/exist',
  QUOTE_SUBMIT_WITH_EMAIL: '/quote/submit-with-email',
  TAX_CALCULATION: '/tax-calculation',
  PATCH_RESTORE_DEAL_ACTION: '/deals/restore-deal-action',
  auth_IG_Verification: 'auth/ig-verification',
  EXPENSE: '/expense/add-expense',
  DROPDOWN_ORGANIZATIONS: '/dropdown/organizations',
  DROPDOWN_PRODUCTS: '/dropdown/products',
  AUTH_SEARCH_COMPANY: 'auth/search-company',
  AUTH_IG_VERIFICATION: 'auth/ig-verification',
  PRODUCTS: '/products',
  ORGANIZATIONS: '/organization/get-organizations',
  VIEW_DEALS_NOTES: '/note',
  CONTACTS: '/contact',
  CONTACTS_VIEW: '/contact/contact-view',
  CONTACTS_VIEWS: '/contact/contact-views',
  LIFECYCLE_STAGES: '/lifecycle-stages',
  CONTACT_STATUS: '/contact-status',
  GET_PERMISSIONS_ROLES: '/permissions/role',
  GET_ADMIN_PERMISSIONS_ROLES: '/permissions/super-admin-roles-rights',
  TASK_MANAGEMENT: '/task/management',
  TASK_MANAGEMENT_UNASSIGN_DEAL: '/task/unassign-deal',
  TASK_CUSTOMIZE_COLUMN: '/customized-columns',
  TASK_MANAGEMENT_INSIGHTS: '/task/task-management-insights',
  TASK_MANAGEMENT_FEED: '/activity-log',
  TASK_MANAGEMENT_INSIGHTS_NEW: '/task/task-management-insights-new',
  DEALS_ASSOCIATION: '/deals/get-associations',
  ENQUIRIES: '/enquiries',
  CREATE_ASSOCIATION: '/deals/create-association',
  DELETE_ASSOCIATION: '/deals/delete-association',
  ASSETS_INVENTORY: '/assets/inventory',
  INVENTORY_EXISTING_INCIDENT: '/assets/assets-associate-existing-tickets',
  DELETE_INVENTORY_ASSOCIATIONS_LIST: '/assets/delete-ticket-association',
  ASSETS_INVENTORY_Associations: '/assets/inventory-association-list',
  QUOTE: '/quote',
  QUOTE_SUBMIT: '/quote/submit',
  GET_COMPANY_ORGANIZATION_DROPDOWN: '/dropdown/organizations',
  GET_COMPANY_ACCOUNTS: '/company-accounts',
  SALE_PRODUCTS: '/sales-product',
  ACTIVITY_LOG: '/activity-log',
  DEAL_PIPELINE: '/deal-pipeline',
  GET_PRODUCTS_PERMISSIONS: '/permissions/permissions-by-product',
  VENDOR_LIST: '/vendors/get-vendors',
  POST_VENDOR: '/vendors/add-vendors',
  DELETE_PRODUCT_CATALOG: '/product-catalog/delete-product-catalog',
  ADD_LOCATION: '/location/add-location',
  ADD_CHILD_LOCATION: '/location/add-child-location',
  GET_LOCATION: '/location/get-location',
  PRODUCT_CATALOG_VENDOR_LIST: '/product-catalog/vendor-list',
  ADD_CANNED_RESPONSES: '/canned-responses/add-canned-response',
  GET_CANNED_RESPONSES: '/canned-responses/get-canned-response',
  GET_CONVERSATION_EMAIL: '/email',
  UPDATE_CANNED_RESPONSES: '/canned-responses/update-canned-response',
  DELETE_CANNED_RESPONSES: '/canned-responses/delete-canned-response',
  GET_RESPONSES_LIST: '/canned-responses/get-responses',
  POST_RESPONSE: '/canned-responses/add-responses',
  UPDATE_RESPONSE: '/canned-responses/update-responses',
  MOVE_RESPONSES: '/canned-responses/move-responses',
  DELETE_RESPONSES: '/canned-responses/delete-responses',
  DROPDOWN_FOLDERS: '/dropdown/folders',
  AGENTS_DROPDOWN: '/dropdown/agents',
  PRODUCT_CATALOG_LIST: '/product-catalog/list',
  PRODUCT_CATALOG: '/product-catalog',
  EDIT_PRODUCT_CATALOG: '/product-catalog/edit-product-catalog',
  DELETE_PRODUCT_CATALOG_VENDOR: '/product-catalog/vendors/delete-vendor',
  PRODUCT_CATALOG_POST_VENDOR: `/product-catalog/add-vendor`,
  PRODUCT_CATALOG_LIST_ASSOCIATED_ASSET: `/product-catalog/get-associate-assets`,
  PRODUCT_CATALOG_POST_ASSOCIATED_ASSET: `/product-catalog/add-associate-asset`,
  PRODUCT_CATALOG_DELETE_ASSOCIATED_ASSET: `/product-catalog/delete-associate-asset`,
  PRODUCT_CATALOG_PATCH_VENDOR: `/product-catalog/vendors/edit-vendor`,
  POST_COMPANY_ACCOUNT: '/org-company-account',
  GET_AGENT: '/requester/requester-list',
  GET_ATTACHMENT: '/attachment/get-attachment',
  POST_ATTACHMENT: '/attachment/add-attachment',
  ADD_AGENT: '/agent/add-agent',
  DELETE_AGENT: '/agent/agent-delete',
  EDIT_AGENT: '/agent/edit-agent',
  TASK: '/task',
  UPDATE_TASK: '/task/update-tasks',
  VENDOR_DETAIL_OVERVIEW: '/vendors/get-vendor',
  DROPDOWN_ASSET_TYPE_LIST: `/asset-type/assset-type-list`,
  TICKET_DETAILS: '/ticket',
  REQUESTER_LIST: `/requester/requester-list`,
  CONVERSATION_EMAIL: `/email`,
  EMAIL_VIEW: `/social-components/email`,
  CONVERSATION_OTHERS_EMAIL_VIEW: `/social-components/email/others/conversations`,
  CONVERSATION_GMAIL_EMAIL_VIEW: `/social-components/email/gmail/conversations`,
  CONVERSATION_OUTLOOK_EMAIL_VIEW: `/social-components/email/outlook/conversations`,
  DROPDOWN_TASK: '/task',
  PURCHASE_ORDER_LIST: `/assets/purchaseorderlist`,
  GET_SOFTWARE_USER: '/assets/software-users-details',
  DEPARTMENT: '/Department/add-department',
  DROPDOWN_DEPARTMENT: `/Department/department-list`,
  TICKETS_ASSOCIATES_ASSETS: '/ticket/associate-assets',
  TICKETS_ASSOCIATES: `/association/manage-association`,
  TICKETS_ASSOCIATES_GET: `/association`,
  DROPDOWN_VENDORS_LIST: `/vendors/get-vendors`,
  EDIT_NEW_VENDOR: '/vendors/update-vendor',
  DELETE_NEW_VENDOR: '/vendors/delete-vendor',
  VENDOR: '/vendors/get-vendor',
  CALLS: '/calls',
  POST_CLOSURE_RULES: '/Closure-Rules/add-closure-rules',
  GET_BUSINESS_HOUR: `/business-hour/list`,
  BUSINESS_HOUR: `/business-hour`,
  DELETE_BUSINESS_HOUR: `/business-hour/delete-business-hour`,
  ADD_BUSINESS_HOUR: `/business-hour/add-business-hours`,
  UPDATE_BUSINESS_HOUR: `/business-hour/update-business-hours`,
  GET_HOLIDAYS: `/business-hour/holidays`,
  ADD_HOLIDAY: `/business-hour/add-holiday`,
  DELETE_HOLIDAY: `/business-hour/delete-holiday`,
  COMPANY: `/companies`,
  DELETED_COMPANIES: '/companies/deleted',
  COMPANY_PREVIEW: '/companies/get-company-preview',
  COMPANY_DEALS: '/deals/get-company-deals',
  RESTORE_COMPANIES: '/companies/restore-action',
  MERGE_COMPANIES: '/companies/merge-company',
  REASSIGN_COMPANY_OWNER: '/companies/change-company-owner',
  GET_COMPANY_ASSOICATION: '/companies/get-company-associations',
  COMPANY_VIEWS: '/company-views',
  CUSTOMIZE_COLUMNS: '/customized-columns',
  DROPDOWN_ACCOUNTS_ROLE: '/dropdown/company-accounts-roles',
  GET_PRODUCT_VENDOR_LIST: '/product-catalog/vendor-product-list',
  POST_PRODUCT_VENDOR: '/product-catalog/add-vendor',
  PUT_PRODUCT_VENDOR: '/product-catalog/vendors/edit-vendor',
  GET_DEPARTMENT: '/Department/department-list',
  DELETE_REQUESTER: '/requester/delete-requester',
  DELETE_SOFTWARE: '/assets/delete-software',
  DELETE_ATTACHMENT: '/attachment/delete-attachment',
  REQUESTER_VIEW_DETAILS: '/requester/view-requester-details/',
  ADD_REQUESTER: '/requester/add-requester',
  EDIT_REQUESTER: '/requester/edit-requester',
  EDIT_ATTACHMENT: '/attachment/edit_attachment',
  USERS_LIST_ADMIN: '/users',
  CATALOG_SERVICES: '/service-catalog/get-category-list',
  SERVICE_CATALOG: '/service-catalog/get-category-list',
  ADD_SERVICE_CATALOG: '/service-catalog/add-category',
  DELETE_SERVICE: '/service-catalog/delete-service',
  UPSERT_SERVICES_CATALOG: '/service-catalog/add-service',
  SERVICE_CATALOG_CATEGORIES: '/service-catalog/get-categories',
  LEADER_BOARD_ADD_AWARD_POINTS: `/Leader-Board/add-award-points`,
  LEADER_BOARD_GET_AWARD_POINTS: `/Leader-Board/get-award-points`,
  LEADER_BOARD_ADD_AGENT_LEVELS: `/Leader-Board/add-agent-levels`,
  LEADER_BOARD_GET_AGENT_LEVELS: `/Leader-Board/get-agent-levels`,
  GET_ASSET_TYPE: '/asset-type/assset-type-list',
  POST_ASSET_TYPE: '/asset-type',
  PATCH_ASSET_TYPE: '/asset-type/add-child-asset-type',
  EDIT_ASSET_TYPE: '/asset-type/edit-assset-type',
  PUT_LOCATION: '/location/edit-location',
  DELETE_CHILD_LOCATION: '/location/delete-child-location',
  GET_BY_ID_LOCATION: '/location/get-location-details',
  DELETE_PARENT_LOCATION: '/location/delete-parent-location',
  DROPDOWN_REQUESTERS: `/requester/requester-list`,
  DROPDOWN_AGENTS: `/requester/requester-list`,
  DROPDOWN_ASSET: 'dropdown/all-assets',
  DROPDOWN_ASSOCIATE_ASSET: `/assets/inventory`,
  DROPDOWN_CATEGORIES: `/service-catalog/get-categories`,
  GET_CHILD_TICKETS: `/ticket/get-child-tickets`,
  ADD_CHILD_TICKET: `/ticket/add-child-ticket`,
  DELETE_CHILD_TICKET: `/ticket/delete-child-tickets`,
  SERVICES_CATEGORIES: `/service-catalog/get-category-list`,
  DEPARTMENT_LIST: `/Department/department-list`,
  EDIT_SERVICE_CATALOG: '/service-catalog/update-service',
  TICKETS_DETACH_ASSOCIATES_ASSETS: '/ticket/detach-assets',
  AUTH_ACCOUNTS: '/auth/accounts',
  AUTH_ACCOUNTS_SELECT: '/auth/accounts/select',
  AUTH_MY_ACCOUNT: '/auth/me',
  EMAIL_EXIST: '/users/email/exist',
  ASSETS_SOFTWARE: '/assets/get-software',
  SOFTWARE_OVERVIEW: '/assets/software_overview',
  SOFTWARE_CONTRACT_UTILIZATION: '/assets/software-contract-utilization',
  SOFTWARE_CONTRACT_VALUE: '/assets/software-contract-value',
  SOFTWARE_ASSIGN_CATEGORY: '/assets/assign-category',
  GET_PRODUCT_VENDOR_DROPDOWN: '/product-catalog/list',
  GET_PRODUCT_DROPDOWN: '/product-catalog/list',
  CALL_WIDGET: `/calls/get-scheduled-call-widget`,
  GET_AGENT_REQUESTER: '/agent/agent-requester-list',
  GET_ASSETS_CONTRACT: '/contract/get-contracts',
  ASSETS_CONTRACT: '/contract',
  VENDOR_DROPDOWN: '/vendors/get-vendors',
  CONTRACT_TYPE_DROPDOWN: '/contract-type',
  DROPDOWN_AGENTS_LIST: '/dropdown/agents',
  GET_PURCHASE_ORDER_OVERVIEW: '/assets/purchaseorder',
  ASSETS_CONTRACT_DELETE: '/contract/{id}',
  KNOWLEDGE_BASE_ARTICLES: `/articles/get-all-articles`,
  KNOWLEDGE_BASE_ARTICLE: `/articles/get-by-id`,
  POST_KNOWLEDGE_BASE_ARTICLES: `/articles`,
  DELETE_KNOWLEDGE_BASE_ARTICLES: `/articles`,
  PURCHASE_ORDER_ASSOCIATIONS: '/assets/purchaseorderassociate',
  PURCHASE_ORDER_ADD_ASSOCIATIONS: '/assets/add-associate-order',
  PURCHASE_ORDER_DELETE_ASSOCIATIONS: '/assets/delete-associate-order',
  DROPDOWN_LOCATION: '/location/get-location',
  DROPDOWN_USERS: '/dropdown/all-users',
  DROPDOWN_ALL_ASSETS: '/dropdown/all-assets',
  ASSETS_INVENTORY_SOFTWARE: '/assets/get-inventory-software',
  DELETE_INVENTORY_SOFTWARE: '/assets/delete-software',
  CHANGE_PASSWORD: '/auth/change-password',
  AGENT_REJECT_REQUEST: '/agent/reject-request',
  APPROVED_REQUEST: '/agent/approve-request',
  ADD_SOFTWARE_USERS: '/assets/add-software-users',
  PATCH_INVENTORY_EXPENSE: '/expense/update-expense',
  DELETE_INVENTORY_EXPENSE: '/expense/delete-expense',
  ASSETS_INVENTORY_DETAIL: '/assets/get-inventory-detail',
  ASSETS_EDIT_INVENTORY: '/assets/edit-inventory',
  CONTACT_NOTE: '/contact-note/note',
  CONTACT_CALL: `/contact-call/call`,
  CONTACT_GROUPS: `/contact/group`,
  ASSIGN_CONTACT_OWNER: `/contact/assign-contact-owner`,
  ADD_CONTRACT: `/contract/add-contract`,
  EDIT_CONTRACT: `/contract/update`,
  UPDATE_CONTRACT_STATUS: `/contract/renew-extend`,
  DELETED_CONTACT_LIST: `/contact/contact-deleted-list`,
  CONTACT_RESTORE: `/contact/restore`,
  CONTACT_DELETE_PERMANENT: `/contact/permanent`,
  CONTACT_ASSOCIATIONS: `/contact/contact-associations`,
  CONTACT_TASKS: `/contact/contact-tasks`,
  ADD_SOFTWARE_INSTALLATION: '/assets/add-software-device',
  REMOVE_SOFTWARE_INSTALLATION: '/assets/software-device/{id}',
  SOFTWARE_INSTALLATION: '/assets/software-devices',
  GET_INVENTORY_OVERVIEW: `/assets/get-inventory-detail`,
  ASSETS_DROPDOWN: '/assets/inventory',
  CREATE_FOLDER: '/articles/create-folder',
  ARTICLES_FOLDERS: '/articles/folders',
  CONTRACT_DROPDOWN: '/dropdown/all-contracts',
  USERS_DROPDOWN: '/dropdown/all-users',
  ALLOCATE_CONTRACT: '/assets/software-allocate-contract',
  DEALLOCATE_CONTRACT: '/assets/software-deallocate-contract',
  REMOVE_CONTRACT: '/assets/software-users-remove',
  GET_SOFTWARE_DETAIL: '/assets/get-software-details',
  DROPDOWN_ASSETS: '/dropdown/all-assets',
  ASSETS_INVENTORY_PURCHASE_ORDER: '/assets/inventory-purchase-order-list',
  ASSETS_INVENTORY_CONTRACTS: '/assets/inventory-contract-list',
  DEPARTMENT_UPDATE: '/Department/update-department',
  DEPARTMENT_DELETE: '/Department/delete-department',
  ASSETS_PURCHASEORDER_DETAIL: '/assets/purchaseorder',
  ASSETS_PURCHASEORDER: '/assets/purchase_order_inventory',
  EDIT_NEW_PURCHASEORDER: '/assets/update_purchase_order_inventory',
  DROPDOWN_SOFTWARE: `/assets/get-software`,
  DROPDOWN_ALL_AGENTS: '/dropdown/agents',
  EDIT_NEW_ITEM: '/assets/purchaseorder',
  PURCHASE_ORDER_STATUS: '/assets/status-purchaseorder',
  VENDOR_PRODUCT_DROPDOWN: `/product-catalog/vendor-product-list`,
  PURCHASE_ORDER: `/assets/purchaseorder`,
  GET_SINGLE_ASSETS_CONTRACT: '/contract/get-contract',
  GET_CONTRACTS_OVERVIEW: '/contract/get-contract',
  GET_DASHBOARD_TICKETS: '/air-services-dashboard/tickets',
  GET_DASHBOARD_CARDS_TICKETS: '/air-services-dashboard/dashboard-tickets',
  DASHBOARD_ANNOUNCEMENTS: '/air-services-dashboard/dashboard-annoucement',
  DASHBOARD_ANNOUNCEMENTS_CUSTOMER:
    '/air-services-dashboard/get-all-customer-announcment',
  DASHBOARD_RECENT_ACTIVITIES:
    '/air-services-dashboard/dashboard-recent-activities',
  DASHBOARD_AGENT_AVAILABILITY: '/air-services-dashboard/get-dashboard-agents',
  ADD_APPROVALS_TICKETS: `/ticket/add-ticket-approval`,
  GET_APPROVAL_TICKETS: `/ticket/get-tickets-approval`,
  UPDATE_APPROVAL_TICKETS: `/ticket/edit-ticket-approval`,
  GET_UNAPPROVED_ARTICLES: `/articles/unapproved-articles`,
  ASSET_TYPE_DROPDOWN: `/asset-type/drop-down-asset-type`,
  ADD_WORKLOAD_SCHEDULE: `/Work-Shchedule/add-work-shchedule`,
  EDIT_WORKLOAD_SCHEDULE: `/Work-Shchedule/edit-work-shchedule`,
  DELETE_WORKLOAD_SCHEDULE: `/Work-Shchedule/delete-work-shchedule`,
  GET_ALL_ARTICLES: '/articles/get-all-articles',
  GET_KNOWLEDGE_BASE_FOLDER: '/articles/folders',
  GET_SINGLE_KNOWLEDGE_BASE_ARTICLES: '/articles/get-by-id',
  GET_RECENT_TICKET: `/air-services-dashboard/recent-tickets-dashboard`,
  GET_TICKETS_PENDING_FOR_APPROVAL: `/air-services-dashboard/get-tickets-approval-dashboard`,
  GET_RECEIVERS_BANK_ACCOUNTS: `/receiver-bank-account`,
  GET_CUSTOMER_DASHBOARD: `/air-services-dashboard/get-customer-dashboard-data`,
  GET_DROPDOWN_COMPANY: `/super-admin/company-list`,
  POST_BUYER_INFO: '/quote/add-buyer-info',
  GET_CUSTOMER_DASHBOARD_ANNOUNCEMENTS: `/air-services-dashboard/get-all-customer-announcment`,
  REQUEST_APPROVAL: `/assets/add-approver-order`,
  REQUEST_APPROVALS_LIST: `/assets/get-purchase-approvals-by-purchase-order`,
  PATCH_APPROVAL_STATUS: `/assets/approver-order-status`,
  ASSETS_RECEIVED: '/assets/get-purchaseorder-assets-received/{id}',
  GET_SMS_DASHBOARD_INSIGHTS: '/sms-marketing/dashboard-insights',
  GET_SMS_MARKETING_BROADCAST: '/sms-marketing/broadcast',
  DELETE_SMS_MARKETING_BROADCAST: '/sms-marketing/broadcast/{smsBroadcastId}',
  GET_IS_PHONE_CONNECTED: '/sms-marketing/connected-number',
  GET_SMS_TEMPLATES: '/sms-marketing/template',
  CONNECT_PHONE_NUMBER: '/sms-marketing/connect-number',
  WHATSAPP_TEMPLATE: '/whatsapp-marketing/template',
  SALES_TEAM: '/teams',
  SALES_TEAM_USERS: '/quote/team/user',
  SERVICE_CATALOG_CATEGORIES_DETAILS: '/service-catalog/get-detail-service',
  UPDATE_CONTRACT_SUBMIT_APPROVAL: '/contract/approval-request',
  GET_CONTRACT_VENDOR_LIST: '/vendors/get-vendor-contracts',
  POST_ARTICLES_FEEDBACK: '/articles/feedback',
  SOFTWARE_CONTRACTS: '/assets/get-software-contracts',
  GET_CLOSURE_RULES: '/Closure-Rules/get-closure-rules',
  ADD_SOFTWARE: '/assets/add_software',
  EDIT_SOFTWARE: '/assets/edit-software',
  UPDATE_CONTRACT_APPROVE: '/contract/approve-contract',
  UPDATE_CONTRACT_REJECT: '/contract/reject-contract',
  PRODUCTS_USERS: '/product-users',
  PRODUCT_ALL_USERS: '/quote/all/user',
  AVAILABLE_USERS: '/quote/team/user',
  POST_APPROVALS: `/articles/approve`,
  GET_KNOWLEDGE_INSIGHTS: `/articles/knowledge-insights`,
  GET_KNOWLEDGE_INSIGHTS_DETAILS: `/articles/knowledge-insights/tickets`,
  POST_CHANGE_PASSWORD: '/auth/change-password',
  GET_TICKET_APPROVAL_DETAILS: `/air-services-dashboard/get-tickets-approval-dashboard-details`,
  ATTACHMENT_INVENTORY: 'attachment/get-attachment',
  UPDATE_CONTRACT: 'contract/renew-extend',
  GET_WORKLOAD_SCHEDULE_LIST: `/Work-Shchedule/get-work-shchedule-list`,
  GET_SINGLE_WORKLOAD_SCHEDULE_DETAILS: `/Work-Shchedule/get-work-shchedule-details`,
  PROFILE_DETAIL: '/users',
  PERMISSIONS_ROLE: '/permissions/role',
  GET_TICKET_BY_REQUESTER: '/ticket/requester-ticket',
  GET_TICKET_BY_SUBJECT: '/ticket/search-subject-ticket',
  MERGE_TICKET: '/ticket/merge-ticket',
  DELETE_ALL_ATTACHMENT: '/attachment/delete-all-attachment',
  DELETE_MULTIPLE_ATTACHMENT: '/attachment/delete-multiple-attachment',
  SINGLE_DEPARTMENT_DETAIL: `/Department/get-by-id`,
  TICKET_NEW_EMAIL: `/email`,
  DELETE_INVENTORY_PURCHASE_ORDER: '/assets/delete-purchase-association',
  DELETE_INVENTORY_CONTRACT: '/assets/delete-contract-association',
  CUSTOMER_GET_COMPANY_ACCOUNTS: `/users/company-accounts`,
  AGENTS_SOFTWARE_LIST: `/agent/agent-software-list`,
  EDIT_SOFTWARE_CATEGORY: `/assets/edit-software-category`,
  HEADER_NOTIFICATIONS: '/notifications',
  SEEN_NOTIFICATIONS: '/notifications/seen',
  CONVERT_TO_AGENT: `/requester/agent-requests`,
  SERVICES_PATCH_EMAIL_NOTIFICATION: `/notifications/settings`,
  SERVICES_GET_EMAIL_NOTIFICATION: `/notifications/get-notification-settings`,
  GET_TOP_PERFORMER: `/air-services-dashboard/get-top-performer`,
  DASHBOARD_EMAIL: `/air-services-dashboard/emailed-dashboards`,
  GET_SETTING_NOTIFICATIONS: '/notifications/get-notification-settings',
  UPDATE_SETTING_NOTIFICATIONS: '/notifications/settings',
  GET_DISCUSSION_OF_TICKET_CONVERSATION: `/discussion/get-discussion`,
  ADD_DISCUSSION_OF_TICKET_CONVERSATION: `/discussion/add_discussion`,
  UPDATE_DISCUSSION_OF_TICKET_CONVERSATION: `/discussion/update-discussion`,
  DELETE_DISCUSSION_OF_TICKET_CONVERSATION: `/discussion/delete-discussion`,
  EDIT_TICKET_CONVERSATION_NOTE: `/email/edit-note`,
  DELETE_TICKET_CONVERSATION: `/email/delete-note`,
  SEND_TICKET_APPROVAL_REMINDER: `/ticket/send-reminder-ticket-approval`,
  SEND_PURCHASE_APPROVAL_REMINDER: `/assets/send-reminder-purchase-approval`,
  IMPORT_FILE: `/import-file`,
  IMPORT_FILE_GET_SIGNED_URL: `/import-file/create-signed-url`,
  GET_PLAN_PRODUCTS_PERMISSIONS: '/plan/plan-product-permissions',
  GET_RULES_AND_TIERS_LIST: `/rules-and-tiers`,
  ADD_RULES: `/rules-and-tiers/rule`,
  ADD_TIERS: `/rules-and-tiers/tier`,
  UPDATE_TIERS: `/rules-and-tiers/tier`,
  CREATE_DIGITAL_REWARD: `/rewards/create-digital-reward`,
  CREATE_PHYSICAL_REWARD: `/rewards/create-physical-reward`,
  GET_REWARDS_LIST: `/rewards/rewards-list`,
  GET_VOUCHERS_REWARDS_DROPDOWN: `/vouchers/list-voucher`,
  TIERS_DROPDOWN_FOR_REWARDS: `/rules-and-tiers/tiers`,
  LEAD_CAPTURE_CTA: '/lead-capture-cta',
  DELETE_LEAD_CAPTURE_CTA: '/lead-capture-cta/multiple',
  CREATE_SHOP: `/shops/create-shops`,
  GET_SHOP_LIST: `/shops/shops-list`,
  UPDATE_SHOP: `/shops/update-shops`,
  SHOP_DETAIL: `/shops/shop-details`,
  GET_RULES_LIST: `/rules-and-tiers/rules`,
  GET_TIERS_LIST: `/rules-and-tiers/tiers`,
  GET_TIERS_BY_ID: `/rules-and-tiers/tier`,
  ADD_VOUCHERS: '/vouchers/create-voucher',
  DELETE_SHOP: `/shops/delete-shops`,
  GET_VOUCHERS: '/vouchers/list-voucher',
  GET_SINGLE_VOUCHERS: '/vouchers/get-voucher-details',
  UPDATE_VOUCHERS_STATUS: '/vouchers/update-voucher-status',
  ADD_LOYALTY_TRANSACTION: `/Transactions/add-transaction`,
  GET_LOYALTY_TRANSACTION: `/Transactions/get-transaction-details`,
  CHANGE_RULES_STATUS: `/rules-and-tiers/rule`,
  NEW_IMPORT_FILE: `/new-import-file/new-import-file`,
  SIGN_UP_LEADS: '/contact/signup-leads',
  GET_GOOGLE_CALENDAR: '/auth/google-calendar/authorize',
  GET_CALENDARS: '/meeting-settings/list',
  CALENDARS_STATUS: '/meeting-settings',
  GET_MEETINGS_LOCATIONS: '/meeting-time-slots/get-meeting-loation',
  ADD_MEETINGS_LOCATIONS: '/meeting-time-slots/add-meeting-loation',
  UPDATE_MEETINGS_LOCATIONS: '/meeting-time-slots/edit-meeting-loation',
  DELETE_MEETINGS_LOCATIONS: '/meeting-time-slots/delete-meeting-loation',
  TIME_SLOTS: '/meeting-time-slots/add-time-slots',
  GET_ASSOCIATION: `/association`,
  POST_ASSOCIATION: `/association/manage-association`,
  DELETE_TASKS: `/task/ids`,
  GET_OFFICE_365_CALENDAR: '/auth/office365-calendar/authorize',
  GET_MS_TEAMS: '/auth/msteams/authorize',
  GET_GOOGLE_MEET: '/auth/google-meet/authorize',
  CREATE_FEEDBACK_SURVEY: '/feedback-survey/create-feedback-survey',
  CLONE_FEEDBACK_SURVEY: '/feedback-survey/clone-survey',
  UPDATE_FEEDBACK_SURVEY: '/feedback-survey/update-feedback-survey',
  GET_FEEDBACK_LIST: '/feedback-survey/list-feedback-survey',
  GET_SINGLE_FEEDBACK: '/feedback-survey/get-feedback-survey',
  DELETE_FEEDBACK_SURVEY: '/feedback-survey/delete-feedback-survey',
  DELETE_FEEDBACK_SURVEY_SECTION:
    '/feedback-survey/delete-feedback-survey-section',
  DELETE_FEEDBACK_SURVEY_QUESTION: '/feedback-survey/delete-question',
  ADD_FEEDBACK_QUESTIONS: '/feedback-survey/add-feedback-survey-questions',
  MERGE_FEEDBACK_SECTION: '/feedback-survey/merge-section',
  CLONE_FEEDBACK_SECTION: '/feedback-survey/clone-survey-section',
  SET_SURVEY_DEFAULT: '/feedback-survey/set-servey-default',
  GET_ZOOM_AUTH: '/auth/zoom/authorize',
  GET_TIME_SLOTS: '/meeting-time-slots/get-time-slots',
  PUT_DYNAMIC_FIELDS: `/customized-columns/create-or-update-custom-fields`,
  GET_DYNAMIC_FIELDS: `/customized-columns/get-custom-field`,
  DELETE_DYNAMIC_FIELDS: `/customized-columns/delete-field`,
  CATEGORY_DROPDOWN: '/product-categories',
  GET_SINGLE_FEEDBACK_FOR_RESPONSE:
    '/feedback-survey/get-survey-questions-by-uuid',
  PATCH_SINGLE_FEEDBACK_ANSWERS_FOR_RESPONSE:
    '/feedback-survey/add-feedback-survey-questions-answer',
  PATCH_SINGLE_FEEDBACK_DROPOUT_ANSWERS_FOR_RESPONSE:
    '/feedback-survey/dropout-by-uuid',
  GET_SINGLE_SURVEY_ALL_RESPONSES_DETAILS:
    '/feedback-survey/get-survey-responses-details',
  ADD_MEETING: '/Meetings/add-meeting',
  GET_GENERIC_REPORTS: `/generic-reports`,
  GET_SINGLE_DEFAULT_CUSTOMER_SURVEY:
    '/feedback-survey/get-default-feedback-survey',
  CHECK_SINGLE_DEFAULT_CUSTOMER_SURVEY_SUBMITTED:
    '/feedback-survey/check-survey-submitted',
  GET_AIR_SERVICES_DASHBOARD_LIST: `/air-services-dashboard`,
  GET_SINGLE_AIR_SERVICES_DASHBOARD: `/air-services-dashboard/get-dynamic-dashboard`,
  CREATE_AIR_SERVICES_DASHBOARD: `/air-services-dashboard/create-dynamic-dashboard`,
  EDIT_AIR_SERVICES_DASHBOARD: `/air-services-dashboard/edit-dynamic-dashboard`,
  DASHBOARD_DROPDOWN: `/air-services-dashboard`,
  MEETINGS_TEMPLATE: '/Meetings/create-meeting-template',
  POST_MEETINGS: '/Meetings/edit-meeting',
  DELETE_MEETINGS: '/Meetings/delete-meeting',
  GET_MEETINGS_LIST: '/Meetings/get-meeting',
  GET_BY_ID_MEETINGS: '/Meetings/get-meeting-by-id',
  GET_RESTORE_GENERIC_REPORTS_LIST: `/generic-reports/list-deleted-generic-reports`,
  DELETE_GENERIC_REPORTS: `/generic-reports/delete-generic-reports`,
  SERVICE_DASHBOARD_DROPDOWN: `/air-services-dashboard`,
  SALES_DASHBOARD_DROPDOWN: `/sales-dashboard`,
  GOALS: '/goals',
  GET_SINGLE_GOAL: '/goals/broadcast',
  DELETE_SERVICES_DASHBOARD: `/air-services-dashboard/delete-dashboards`,
  SOFT_DELETE_GENERIC_REPORTS: `/generic-reports/soft-delete-generic-reports`,
  RESTORE_DELETED_GENERIC_REPORTS: `/generic-reports/restore-deleted-generic-reports`,
  HARD_DELETE_GENERIC_REPORTS: `/generic-reports/hard-delete-generic-reports`,
  CLONE_GENERIC_REPORTS: `/generic-reports/clone-generic-report`,
  UPDATE_GENERIC_REPORTS_ACTION: `/generic-reports/update-generic-report-action`,
  GET_SINGLE_GENERIC_REPORT_DETAIL: `/generic-reports/get-generic-report-details`,
  CHANGE_DEFAULT_AIR_SERVICES_DASHBOARD: `/air-services-dashboard/edit-default-option`,
  UPDATE_LINK_DASHBOARDS_REPORTS_ACTION: `/generic-reports/update-link-dashboard`,
  MARKETING_DASHBOARD_LISTS_DROPDOWN: `/marketing-dashboard`,
  CONTRACT_TYPE_SERVICES_SETTINGS: `/contract-type`,
  GET_MEETINGS_SLOTS: '/meeting-time-slots/suggested-time-slots',
  GET_BOOKED_MEETINGS_SLOTS: '/meeting-time-slots/booked_slots',
  EXPORT_GENERIC_REPORTS: `/generic-reports/export-reports`,
};

export const LEAD_CAPTURE_FORM = {
  CREATE_FORM: '/lead-capture-form/create-form',
  GET_FORM: '/lead-capture-form/get-forms',
  GET_FORM_BY_ID: '/lead-capture-form/get-form',
  UPDATE_FORM: '/lead-capture-form/update-form',
  DELETE_FORM: '/lead-capture-form/delete-form',
  PUT_ADD_VIEW_FORM: '/lead-capture-form/add-view-form',
  POST_MANAGE_FIELDS: '/lead-capture-form/manage-lead-form-fields',
  GET_MANAGE_FIELD: '/lead-capture-form/get-form-field',
  GET_FORM_SUBMISSIONS: '/lead-capture-form/get-lead-capture-submissions',
  GET_SUBMISSION_EMAIL:
    '/lead-capture-form/get-lead-capture-submissions-emails',
  POST_FORM_SUBMISSIONS: '/lead-capture-form/lead-capture-submission',
  GET_RESTORE_FORMS: '/lead-capture-form/get-lead-capture-soft-deleted-forms',
  DELETE_FORM_PERMANENT: '/lead-capture-form/permanent-delete-forms',
  PATCH_RESTORE_FORM: '/lead-capture-form/restore-deleted-forms',
};

export const EMAILS_MARKETING = {
  EMAIL_MARKETING: '/emails-marketing/get-all-marketingEmails',
  CREATE_EMAIL: '/emails-marketing/create-email',
  DELETE_EMAIL: '/emails-marketing/delete-email',
};

export const superAdminBillingInvoices = {
  GET_ORG_PLAN: '/super-admin/get-all-orgplans?',
  GET_PRODUCTS: '/products?status=active',
  GET_PLAN_TYPE: '/plan/plan-type-list',
  GET_ORGANIZATION: '/organization/get-organizations',
  POST_BILING_INVOICES: '/super-admin/assign-plan',
  GET_PLAN_ID: '/super-admin/find-plan',
  PATCH_ASSIGN_PLAN: '/super-admin/update-assign-plan',
  GET_ALL_INVOICE: '/super-admin/get-all-invoice',
  UPDATE_INVOICE: '/super-admin/update-invoice',
  GET_CRM: '/super-admin/get-all-crm-plans',
  FIND_CRM: '/super-admin/find-crm',
  UNASSIGN_PLAN: '/super-admin/unassign-plan',
};

export const organization = {
  POST_ORGANIZATION_ACCOUNT: '/org-company-account',
  GET_ORGANIZATION_ACCOUNT_ALL: '/org-company-account/get-accounts',
  GET_PRODUCTS_ALL: '/products',
  GET_ORGANIZATION_ACCOUNT_ID: '/org-company-account',
  GET_MAIN_ORGANIZATION: '/organization',
  UPDATE_ORGANIZATION_ACCOUNT: '/org-company-account',
  UPDATE_ORGANIZATION_ACCOUNT_STATUS: '/org-company-account/update-status',
  DELETE_ORGANIZATION_ACCOUNT: '/org-company-account',
  DELETE_ORGANIZARION_MULTIPLE: '/org-company-account/delete-multiple',
  USERS_PRODUCTS: '/users/products',
};

export const settingSalesProductCategory = {
  POST_SALES_PRODUCT_CATEGORY: '/product-categories',
  GET_SALES_PRODUCT_CATEGORY: '/product-categories',
  UPDATE_SALES_PRODUCT_CATEGORY: '/product-categories',
};
export const settingLifeCycleStage = {
  POST_LIFE_CYCLE_STAGE: '/lifecycle-stages',
  GET_LIFE_CYCLE_STAGE: '/lifecycle-stages',
  GET_LIFE_CYCLE_STAGE_ID: '/lifecycle-stages',
  UPDATE_LIFE_CYCLE_STAGE: '/lifecycle-stages',
  DELETE_LIFE_CYCLE_STAGE: '/lifecycle-stages',
};

export const settingContactStatus = {
  POST_CONTACT_STATUS: '/contact-status',
  GET_CONTACT_STATUS: '/contact-status',
  GET_CONTACT_STATUS_ID: '/contact-status',
  UPDATE_CONTACT_STATUS: '/contact-status',
  DELETE_CONTACT_STATUS: '/contact-status',
};
export const ORG_ADMIN = {
  SUBSCRIPTION_AND_INVOICES: '/org-admin/subscriptions',
  SUBSCRIPTION_AND_INVOICES_UN_ASSIGN_PLAN:
    '/org-admin/subscriptions/unassign-plan',
  SUBSCRIPTION_AND_INVOICES_TAX_CALCULATIONS: '/tax-calculation/apply-on/',
  SUBSCRIPTION_AND_INVOICES_CRM:
    '/org-admin/subscriptions/get-all-crm-with-subscription',
  GET_INVOICES: '/org-admin/invoices',
  PRODUCT_PLAN_LIST: '/plan/product-plan-list',
  PRODUCT_CRM_PLAN_LIST: '/super-admin/get-one-crm-plans',
  ACTIVITY_LOG: '/activity-log',
  ACTIVITY_LOG_SUB: '/activity-log/sub-activities',
  SETTINGS_CONTACT_STATUS: '/contact-status',
  PRODUCT_DROPDOWN: '/dropdown/products',
};

export const COMMON_DOCUMENTS = {
  POST_DOCUMENTS_FOLDER: '/documents/folder',
  POST_DOCUMENTS_FILE: '/documents/file',
  GET_DOCUMENT_FOLDER: '/documents/folders',
  GET_DOCUMENT_FILE: '/documents/files',
  PATCH_DOCUMENT_FOLDER_ID: '/documents/folder',
  PATCH_DOCUMENT_FILE_ID: '/documents/file',
  DELETE_DOCUMENT_FOLDER_ID: '/documents/folder',
  DELETE_DOCUMENT_FILE_ID: '/documents/files',
};

export const INVOICE = {
  GET_QUOTE_ID: '/quote',
  POST_INVOICE_QUOTE: '/quote-invoice',
  GET_INVOICE_QUOTE_LIST: '/quote',
};

export const OPERATION = {
  OPERATION_WORKFLOW: '/workflows',
  SCHEMA_KEYS: '/workflows/schema-keys',
  STATUS_WORKFLOW: '/workflows/change-status',
  SAVE_WORKFLOW: '/workflows/save',
  CLONE_WORKFLOW: '/workflows/clone',
  TEST_WORKFLOW: '/workflows/test',
  GET_IMPORT_DATA_MANAGEMENT: '/data-management/get-data-management',
  POST_GENERIC_REPORT: '/generic-reports',
  PATCH_GENERIC_REPORT: '/generic-reports/update-generic-report',
  GET_SINGLE_GENERIC_REPORT: '/generic-reports/get-generic-report-details',
};

export const AIR_SALES = {
  INVOICES: '/quote-invoice',
};

export const SUPER_ADMIN_SETTINGS = {
  FAQS: 'faqs',
};

export const AIR_MARKETER = {
  CAMPAIGNS_VIEW: '/campaigns/view',
  CAMPAIGNS: '/campaigns',
  CAMPAIGNS_TASKS: '/campaigns/task',
  CAMPAIGNS_CLONE: '/campaigns/view/clone',
  CAMPAIGNS_SAVE_VIEW: '/campaigns/view',
  REPORTS_LEADS: '/lead-capture-form/get-all-lead-capture-stats',
};

export const SUPER_ADMIN_DASHBOARD = {
  USER_STATS: '/super-admin/user-stats',
  PLAN_STATS: '/super-admin/plan-stats',
  BILLING_INVOICES: '/super-admin/dashboard',
  PLANS_LIST: '/plan',
  ENQUIRIES: '/super-admin/user-enquiry-wise-stats',
};

export const WHATSAPP_MARKETING = {
  CONNECT_PHONE_NUMBER: '/whatsapp-marketing/connect-number',
  GET_IS_PHONE_CONNECTED: '/whatsapp-marketing/connected-number',
  GET_WHATSAPP_MARKETING_BROADCAST: '/whatsapp-marketing/broadcast',
  GET_WHATSAAP_TEMPLATE: '/whatsapp-marketing/template',
  DELETE_SMS_MARKETING_BROADCAST:
    '/whatsapp-marketing/broadcast/{whatsappBroadcastId}',
};
export const SALES_DASHBOARD = {
  DEALS_CREATED_VS_CLOSE_DATES:
    '/sales-dashboard/deals-created-vs-closed-deals',
  WIDGET:
    '/sales-dashboard/sales-total-deals-open-deals-team-goals-closed-won-published-quotes',
  SALES_DASHBOARD: '/sales-dashboard',
};

export const AIR_MARKETER_EMAIL_FOLDER = {
  GET_EMAIL_FOLDER: '/emails-marketing/get-all-folders',
  POST_EMAIL_FOLDER: '/emails-marketing/create-emails-folder',
  DELETE_EMAIL_FOLDER: '/emails-marketing/delete-folder',
  DUPLICATE_EMAIL_FOLDER: '/emails-marketing/duplicate-folder',
};
