export const END_POINTS = {
  LOGIN: 'auth/signin',
  SIGNUP: 'auth/signup',
  verify_token: 'auth/verify-token',
  search_company: 'auth/signup',
  get_permissions: '/premissions',
  reset_password: 'auth/resetPassword',
  forgot_password: 'auth/forgot-password',
  NEW_INCIDENT: '/ticket',
  WORKLOAD: `/workload/workload-management`,
  INVENTORY_EXPENSE: 'expense/add-expense',
  GET_INVENTORY_EXPENSE: 'expense/get-expense',
  TICKET: '/ticket',
  TICKET_STATUS: '/ticket/status',
  TICKET_BULK_UPDATE: '/ticket/bulk-ticket-update',
  USER_LIST: '/users',
  // USER_LIST: '/users',
  ADD_USER: '/users',
  // GET_USER_DETAILS:'/users',
  ADD_USER_ACCOUNT: '/super-admin/add-accounts',
  USER_ACCOUNTS_LIST: '/super-admin/accounts-list',
  UPDATE_USER_LIST: '/users/edit',
  COMPANY_CRN: '/auth/search-company',
  DROPDOWN_ORGANIZATIONS: '/dropdown/organizations',
  DROPDOWN_PRODUCTS: '/dropdown/products',
  AUTH_SEARCH_COMPANY: 'auth/search-company',
  AUTH_IG_VERIFICATION: 'auth/ig-verification',
};

export const superAdminBillingInvoices = {
  get_org_plan: '/super-admin/get-all-orgplans?',
  get_Products: '/products?status=inactive',
  get_plan_type: '/plan/plan-type-list',
  get_organizations: '/organization/get-organizations',
  post_biling_invoices: '/super-admin/assign-plan',
};

export const organization = {
  post_organization_account: '/org-company-account',
  get_organization_account_all: '/org-company-account/get-accounts',
  get_organization_account_id: '/org-company-account',
  get_main_organization: '/organization',
  update_organization_account: '/org-company-account',
  delete_organization_account: '/org-company-account',
};
