export const cardData = [
  {
    _id: 1,
    icon: '',
    shopName: 'Share my dine',
    shopeType: 'Department',
    associatedEmail: 'Share-my-dine@gmail.com',
    city: 'Department',
    country: 'Department',
    postCode: 'Department',
    address: 'Department',
    date: new Date(),
  },
  {
    _id: 2,
    icon: '',
    shopName: 'Homebase',
    shopeType: 'Web Store                             ',
    associatedEmail: 'Department',
    city: 'Department',
    country: 'Department',
    postCode: 'Department',
    address: 'Department',
    date: new Date(),
  },
  {
    _id: 3,
    icon: '',
    shopName: 'Foster App',
    shopeType: 'Headquarters',
    associatedEmail: 'foster-app@co.uk',
    city: 'London',
    country: 'Uk',
    postCode: 'Headquarters',
    address: 'Headquarters',
    date: new Date(),
  },
  {
    _id: 4,
    icon: '',
    shopName: 'Share my dine',
    shopeType: 'Department',
    associatedEmail: 'Department',
    city: 'Department',
    country: 'Department',
    postCode: 'Department',
    address: 'Department',
    date: new Date(),
  },
  {
    _id: 5,
    icon: '',
    shopName: 'Share my dine',
    shopeType: 'Department',
    associatedEmail: 'Department',
    city: 'Department',
    country: 'Department',
    postCode: 'Department',
    address: 'Department',
    date: new Date(),
  },
  {
    _id: 6,
    icon: '',
    shopName: 'Share my dine',
    shopeType: 'Department',
    associatedEmail: 'Department',
    city: 'Department',
    country: 'Department',
    postCode: 'Department',
    address: 'Department',
    date: new Date(),
  },
];
