import { PROJECT_NAME } from '@/config';
import { BACKEND_COLLECTION_NAME } from '@/constants/api';
import {
  AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS,
} from '@/constants/permission-keys';
import {
  CHARTS,
  FIELD_TYPE,
  GENERIC_REPORT_MODULES,
  REPORT_TYPE,
} from '@/constants/strings';
import { GLOBAL_CHARACTERS_LIMIT } from '@/constants/validation';
import * as Yup from 'yup';

export const defaultValues = () => {
  return {
    chartTitle: 'Report Chart',
    tableTitle: 'Report Table',
    textTitle: 'Report Text',
    xAxis: null,
    xAxisType: [],
  };
};

export const validationSchema = Yup?.object()?.shape({
  chartTitle: Yup?.string()
    ?.trim()
    ?.required('Chart title is required')
    ?.max(
      GLOBAL_CHARACTERS_LIMIT?.DEFAULT,
      `Maximum characters limit is ${GLOBAL_CHARACTERS_LIMIT?.DEFAULT}`,
    ),
  tableTitle: Yup?.string()
    ?.trim()
    ?.required('Table title is required')
    ?.max(
      GLOBAL_CHARACTERS_LIMIT?.DEFAULT,
      `Maximum characters limit is ${GLOBAL_CHARACTERS_LIMIT?.DEFAULT}`,
    ),
  textTitle: Yup?.string()
    ?.trim()
    ?.required('Text title is required')
    ?.max(
      GLOBAL_CHARACTERS_LIMIT?.DEFAULT,
      `Maximum characters limit is ${GLOBAL_CHARACTERS_LIMIT?.DEFAULT}`,
    ),
});

export const fieldsList = [
  {
    id: '0',
    title: 'Chart',
    match: 'chart',
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Text',
    match: 'text',
    description: 'Add context to your report',
  },
  {
    id: '2',
    title: 'Table',
    match: 'table',
    description: 'General Table',
  },
];

export const templateList = [
  {
    id: '0',
    title: 'Tickets Analysis Report',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Status', value: 'status', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Open Tickets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: 'counter',
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Open tickets count',
    fieldName: 'status',
    fieldValue: 'OPEN',
  },
  {
    id: '2',
    title: 'Close Tickets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '12',
    match: 'counter',
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Close tickets count',
    fieldName: 'status',
    fieldValue: 'CLOSED',
  },
  {
    id: '3',
    title: 'Spams Tickets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '1',
    match: 'counter',
    templateType: REPORT_TYPE?.TICKETS,
    description: 'OverDue tickets count',
    fieldName: 'status',
    fieldValue: 'SPAMS',
  },
  {
    id: '4',
    title: 'Resolved Tickets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '15',
    match: 'counter',
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Resolved tickets count',
    fieldName: 'status',
    fieldValue: 'RESOLVED',
  },
  {
    id: '5',
    title: 'Pending Tickets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '4',
    match: 'counter',
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Pending tickets count',
    fieldName: 'status',
    fieldValue: 'PENDING',
  },
  {
    id: '6',
    title: 'Assets Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: {
      label: 'Inventory Asset Type',
      value: 'inventory_assetType',
      ref: BACKEND_COLLECTION_NAME?.ASSET_TYPES,
    },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Visualize your data',
  },
  {
    id: '7',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['assetType', 'locationId', 'departmentId', 'impact'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'assetType',
        collectionName: BACKEND_COLLECTION_NAME?.ASSET_TYPES,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'locationId',
        collectionName: BACKEND_COLLECTION_NAME?.LOCATION,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'departmentId',
        collectionName: BACKEND_COLLECTION_NAME?.DEPARTMENT,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'impact',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'General table',
  },
  {
    id: '8',
    title: 'Total Assets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '10',
    match: 'counter',
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Total inventory assets count',
  },
  {
    id: '9',
    title: 'Low Impact Assets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: 'counter',
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Inventory assets hardware count',
    fieldName: 'impact',
    fieldValue: 'LOW',
  },
  {
    id: '10',
    title: 'High Impact Assets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: 'counter',
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Inventory assets IT services count',
    fieldName: 'impact',
    fieldValue: 'HIGH',
  },
  {
    id: '11',
    title: 'Medium Impact Assets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '7',
    match: 'counter',
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Inventory assets backup services count',
    fieldName: 'impact',
    fieldValue: 'MEDIUM',
  },
  {
    id: '12',
    title: 'Software Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Status', value: 'status', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Visualize your data',
  },
  {
    id: '13',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['status', 'type'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'type',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'General table',
  },
  {
    id: '14',
    title: 'Total Software',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '1',
    match: 'counter',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Total software report count',
  },
  {
    id: '15',
    title: 'Restricted Software',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '10',
    match: 'counter',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Restricted software report count',
    fieldName: 'status',
    fieldValue: 'Restricted',
  },
  {
    id: '16',
    title: 'Ignored Software',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: 'counter',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Ignored software report count',
    fieldName: 'status',
    fieldValue: 'Ignored',
  },
  {
    id: '17',
    title: 'Managed Software',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: 'counter',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Managed software report count',
    fieldName: 'status',
    fieldValue: 'Managed',
  },
  {
    id: '18',
    title: 'Disabled Software',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '7',
    match: 'counter',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Disabled software report count',
    fieldName: 'status',
    fieldValue: 'Disabled',
  },
  {
    id: '19',
    title: 'InReview Software',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: 'counter',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'InReview software report count',
    fieldName: 'status',
    fieldValue: 'InReview',
  },
  {
    id: '20',
    title: 'Contract Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Contract Type', value: 'contractType', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Visualize your data',
  },
  {
    id: '21',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['type', 'status', 'vendor', 'approver'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'type',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'vendor',
        collectionName: BACKEND_COLLECTION_NAME?.VENDORS,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'approver',
        collectionName: BACKEND_COLLECTION_NAME?.USERS,
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'General table',
  },
  {
    id: '22',
    title: 'Draft Contracts',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '2',
    match: 'counter',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Draft contract count',
    fieldName: 'status',
    fieldValue: 'DRAFT',
  },
  {
    id: '23',
    title: 'Pending Approval Contracts',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: 'counter',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Pending approval contract count',
    fieldName: 'status',
    fieldValue: 'PENDING_APPROVAL',
  },
  {
    id: '24',
    title: 'Approved Contracts',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: 'counter',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Approved contract count',
    fieldName: 'status',
    fieldValue: 'APPROVED',
  },
  {
    id: '25',
    title: 'Active Contracts',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '3',
    match: 'counter',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Active contract count',
    fieldName: 'status',
    fieldValue: 'ACTIVE',
  },
  {
    id: '26',
    title: 'Expired Contract ',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '4',
    match: 'counter',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Expired contract count',
    fieldName: 'status',
    fieldValue: 'EXPIRED',
  },
  {
    id: '27',
    title: 'Rejected Contracts',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: 'counter',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Rejected contract count',
    fieldName: 'status',
    fieldValue: 'REJECTED',
  },
  {
    id: '28',
    title: 'Terminated Contract ',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: 'counter',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Terminated contract count',
    fieldName: 'status',
    fieldValue: 'TERMINATED',
  },
  {
    id: '29',
    title: 'Purchase Order Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Approval Status', value: 'approvalStatus', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Visualize your data',
  },
  {
    id: '30',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['vendorId', 'locationId', 'departmentId', 'status'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'vendorId',
        collectionName: BACKEND_COLLECTION_NAME?.VENDORS,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'locationId',
        collectionName: BACKEND_COLLECTION_NAME?.LOCATION,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'departmentId',
        collectionName: BACKEND_COLLECTION_NAME?.DEPARTMENT,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'General table',
  },
  {
    id: '31',
    title: 'All Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '4',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'All purchase order count',
  },
  {
    id: '32',
    title: 'Ordered Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '7',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Ordered purchase order count',
    fieldName: 'status',
    fieldValue: 'ORDERED',
  },
  {
    id: '33',
    title: 'Open Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Open purchase order count',
    fieldName: 'status',
    fieldValue: 'OPEN',
  },
  {
    id: '34',
    title: 'Cancelled Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '1',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Cancelled purchase order count',
    fieldName: 'status',
    fieldValue: 'CANCELLED',
  },
  {
    id: '35',
    title: 'Received Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Received purchase order count',
    fieldName: 'status',
    fieldValue: 'RECEIVED',
  },
  {
    id: '36',
    title: 'Partly Received Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Partly received purchase order count',
    fieldName: 'status',
    fieldValue: 'PARTLY_RECEIVED',
  },
  {
    id: '37',
    title: 'Approved Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '2',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Approved purchase order count',
    fieldName: 'status',
    fieldValue: 'APPROVED',
  },
  {
    id: '38',
    title: 'Pending Approval Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '3',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Pending approval purchase order count',
    fieldName: 'status',
    fieldValue: 'PENDING_APPROVAL',
  },
  {
    id: '39',
    title: 'Closed Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '4',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Closed purchase order count',
    fieldName: 'status',
    fieldValue: 'CLOSED',
  },
  {
    id: '40',
    title: 'Rejected Purchase Order',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: 'counter',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Received purchase order count',
    fieldName: 'status',
    fieldValue: 'REJECTED',
  },
  {
    id: '41',
    title: 'Deals Analytics',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.DEALS,
    description: 'Visualize your data',
  },
  {
    id: '42',
    title: 'Deals Analytics',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.DEALS,
    description: 'Visualize your data',
  },
  {
    id: '43',
    title: 'Deals Overview',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['dealPipelineId', 'priority', 'billingFrequency'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'dealPipelineId',
        collectionName: BACKEND_COLLECTION_NAME?.DEAL_PIPELINES,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'priority',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'billingFrequency',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.DEALS,
    description: 'General table',
  },
  {
    id: '44',
    title: 'Low priority Deals',
    ticketCount: '6',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    match: 'counter',
    templateType: REPORT_TYPE?.DEALS,
    description: 'Low priority deals count',
    fieldName: 'priority',
    fieldValue: 'Low',
  },
  {
    id: '45',
    title: 'Medium priority Deals',
    ticketCount: '7',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    match: 'counter',
    templateType: REPORT_TYPE?.DEALS,
    description: 'Medium priority deals count',
    fieldName: 'priority',
    fieldValue: 'Medium',
  },
  {
    id: '46',
    title: 'High priority Deals',
    ticketCount: '3',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    match: 'counter',
    templateType: REPORT_TYPE?.DEALS,
    description: 'High priority deals count',
    fieldName: 'priority',
    fieldValue: 'High',
  },
  {
    id: '47',
    title: 'Leads Geerated by CTA',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Form Views', value: 'formViews', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.LEADS,
    description: 'Visualize your data',
  },
  {
    id: '48',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['clickCount', 'viewCount', 'clickRate'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'clickCount',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'viewCount',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'clickRate',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.LEADS,
    description: 'Leads CTA table',
  },
  {
    id: '49',
    title: 'Customized Lead CTA',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '4',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'Customized button type lead CTA count',
    fieldName: 'buttonType',
    fieldValue: 'customized',
  },
  {
    id: '50',
    title: 'Image Lead CTA',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '1',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'Image button type lead CTA count',
    fieldName: 'buttonType',
    fieldValue: 'image',
  },
  {
    id: '51',
    title: 'New Lead CTA',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'New URL redirect type lead CTA count',
    fieldName: 'urlRedirectType',
    fieldValue: 'new',
  },
  {
    id: '52',
    title: 'AAC Page Lead CTA',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: `${PROJECT_NAME} page URL redirect type lead CTA count`,
    fieldName: 'urlRedirectType',
    fieldValue: `${PROJECT_NAME} page`,
  },
  {
    id: '53',
    title: 'AAC Blog Lead CTA',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: `${PROJECT_NAME} blog post page URL redirect type lead CTA count`,
    fieldName: 'urlRedirectType',
    fieldValue: `${PROJECT_NAME} blog post`,
  },
  {
    id: '54',
    title: 'Meeting Link Lead CTA',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '3',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'Meeting link page URL redirect type lead CTA count',
    fieldName: 'urlRedirectType',
    fieldValue: 'meeting link',
  },
  {
    id: '55',
    title: 'File Link Lead CTA',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'File link page URL redirect type lead CTA count',
    fieldName: 'urlRedirectType',
    fieldValue: 'file link',
  },
  {
    id: '56',
    title: 'Total Add Spend',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Status', value: 'status', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'Visualize your data',
  },
  {
    id: '57',
    title: 'Ad Campaigns',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['campaignOwner', 'status'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'campaignOwner',
        collectionName: BACKEND_COLLECTION_NAME?.USERS,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'General table',
  },
  {
    id: '58',
    title: 'Scheduled Campaigns',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '4',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'Scheduled campaigns count',
    fieldName: 'campaignStatus',
    fieldValue: 'scheduled',
  },
  {
    id: '59',
    title: 'InProgress Campaigns',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '2',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'InProgress campaigns count',
    fieldName: 'campaignStatus',
    fieldValue: 'inprogress',
  },
  {
    id: '60',
    title: 'Active Campaigns',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'Active campaigns count',
    fieldName: 'campaignStatus',
    fieldValue: 'active',
  },
  {
    id: '61',
    title: 'Paused Campaigns',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '5',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'Paused campaigns count',
    fieldName: 'campaignStatus',
    fieldValue: 'paused',
  },
  {
    id: '62',
    title: 'Completed Campaigns',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '7',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'Completed campaigns count',
    fieldName: 'campaignStatus',
    fieldValue: 'completed',
  },
  {
    id: '63',
    title: 'Forecast Analytics',
    chartType: CHARTS?.HORIZONTAL_BAR_CHART,
    type: CHARTS?.TEMPLATE_HORIZONTAL_CHART,
    xAxis: {
      label: 'Goals Pipelines',
      value: 'goals_pipelineId',
      ref: BACKEND_COLLECTION_NAME?.FORECAST_PIPELINES,
    },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '64',
    title: 'Comparison',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Goal Name', value: 'goalName', ref: null },
    subFilter: true,
    match: 'chart',
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '65',
    title: 'Overview',
    tableColumns: [
      'goalName',
      'goalPipelineId',
      'target',
      'status',
      'duration',
    ],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'goalName',
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'goalPipelineId',
        collectionName: BACKEND_COLLECTION_NAME?.FORECAST_PIPELINES,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'target',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'duration',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.FORECAST,
    description: 'General table',
  },
];

export const mainMetrics = (setMetricType: any) => {
  return {
    [GENERIC_REPORT_MODULES?.SERVICES]: [
      {
        id: 9707,
        permissionKey: [
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.INVENTORIES,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.INVENTORIES);
          closeMenu?.();
        },
      },
      {
        id: 4768,
        permissionKey: [
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.SOFTWARE,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.SOFTWARE);
          closeMenu?.();
        },
      },
      {
        id: 5758,
        permissionKey: [
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.CONTRACTS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.CONTRACTS);
          closeMenu?.();
        },
      },
      {
        id: 9875,
        permissionKey: [
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.TICKETS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.TICKETS);
          closeMenu?.();
        },
      },
      {
        id: 8569,
        permissionKey: [
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.PURCHASE_ORDER,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.PURCHASE_ORDER);
          closeMenu?.();
        },
      },
    ],
    [GENERIC_REPORT_MODULES?.SALES]: [
      {
        id: 1535,
        permissionKey: [
          AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.DEALS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.DEALS);
          closeMenu?.();
        },
      },
      {
        id: 9765,
        permissionKey: [
          AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.FORECAST,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.FORECAST);
          closeMenu?.();
        },
      },
    ],
    [GENERIC_REPORT_MODULES?.MARKETING]: [
      {
        id: 3575,
        permissionKey: [
          AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.CAMPAIGNS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.CAMPAIGNS);
          closeMenu?.();
        },
      },
      {
        id: 9855,
        permissionKey: [
          AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
          AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
        ],
        title: REPORT_TYPE?.LEADS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.LEADS);
          closeMenu?.();
        },
      },
    ],
  };
};
