import {
  CHARTS,
  COLLECTION_NAME,
  FIELD_TYPE,
  GENERIC_REPORT_MODULES,
  REPORT_TYPE,
} from '@/constants/strings';

export const defaultValues = () => {
  return {
    chartTitle: 'Report Chart',
    tableTitle: 'Report Table',
    textTitle: 'Report Text',
    xAxis: null,
    xAxisType: [],
  };
};
export const fieldsList = [
  {
    id: '0',
    title: 'Chart',
    match: 'chart',
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Text',
    match: 'text',
    description: 'Add context to your report',
  },
  {
    id: '2',
    title: 'Table',
    match: 'table',
    description: 'General Table',
  },
];

export const templateList = [
  {
    id: '0',
    title: 'Tickets Analysis Report',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Status', value: 'status', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Open',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '0',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Open tickets count',
  },
  {
    id: '2',
    title: 'Close',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '12',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Close tickets count',
  },
  {
    id: '3',
    title: 'Over Due',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '1',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.TICKETS,
    description: 'OverDue tickets count',
  },
  {
    id: '4',
    title: 'Unassigned',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '0',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Unassigned tickets count',
  },
  {
    id: '5',
    title: 'Resolved',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '15',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Resolved tickets count',
  },
  {
    id: '6',
    title: 'Pending',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '0',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.TICKETS,
    description: 'Pending tickets count',
  },
  {
    id: '7',
    title: 'Assets Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: {
      label: 'Inventory Asset Type',
      value: 'inventory_assetType',
      ref: COLLECTION_NAME?.ASSET_TYPES,
    },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Visualize your data',
  },
  {
    id: '8',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: [
      'assetType',
      'status',
      'locationId',
      'departmentId',
      'impact',
    ],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'assetType',
        collectionName: COLLECTION_NAME?.ASSET_TYPES,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'locationId',
        collectionName: COLLECTION_NAME?.LOCATION,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'departmentId',
        collectionName: COLLECTION_NAME?.DEPARTMENT,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'impact',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'General Table',
  },
  {
    id: '9',
    title: 'Total Assets',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '10',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Total inventory Assets count',
  },
  {
    id: '10',
    title: 'Hardware',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Inventory assets hardware count',
  },
  {
    id: '11',
    title: 'IT Services',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Inventory assets IT Services count',
  },
  {
    id: '12',
    title: 'Backup Services',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '7',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Inventory assets backup services count',
  },
  {
    id: '13',
    title: 'Utilizable',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.INVENTORIES,
    description: 'Inventory assets utilizable count',
  },
  {
    id: '14',
    title: 'Software Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Status', value: 'status', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Visualize your data',
  },
  {
    id: '15',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['status', 'type'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'type',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'General Table',
  },
  {
    id: '16',
    title: 'Total',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '0',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Total software report count',
  },
  {
    id: '17',
    title: 'Restricted',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '10',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Restricted software report count',
  },
  {
    id: '18',
    title: 'Ignored',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '9',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Ignored software report count',
  },
  {
    id: '19',
    title: 'Managed',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '8',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Managed software report count',
  },
  {
    id: '20',
    title: 'Disabled',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '7',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'Disabled software report count',
  },
  {
    id: '21',
    title: 'InReview',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.SOFTWARE,
    description: 'InReview software report count',
  },
  {
    id: '22',
    title: 'Contract Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Contract Type', value: 'contractType', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Visualize your data',
  },
  {
    id: '23',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['type', 'status', 'vendor', 'approver'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'type',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'vendor',
        collectionName: COLLECTION_NAME?.VENDORS,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'approver',
        collectionName: COLLECTION_NAME?.USERS,
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'General Table',
  },
  {
    id: '24',
    title: 'All',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'All contract count',
  },
  {
    id: '25',
    title: 'Lease',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Lease contract count',
  },
  {
    id: '26',
    title: 'Maintain',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Maintain contract count',
  },
  {
    id: '27',
    title: 'Software',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Software contract count',
  },
  {
    id: '28',
    title: 'Warranty',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.CONTRACTS,
    description: 'Warranty contract count',
  },
  {
    id: '29',
    title: 'Purchase Order Distribution',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Approval Status', value: 'approvalStatus', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Visualize your data',
  },
  {
    id: '30',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['vendorId', 'locationId', 'departmentId', 'status'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'vendorId',
        collectionName: COLLECTION_NAME?.VENDORS,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'locationId',
        collectionName: COLLECTION_NAME?.LOCATION,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'departmentId',
        collectionName: COLLECTION_NAME?.DEPARTMENT,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'General Table',
  },
  {
    id: '31',
    title: 'All',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'All purchase order count',
  },
  {
    id: '32',
    title: 'Approved',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Approved purchase order count',
  },
  {
    id: '33',
    title: 'Rejected',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Rejected purchase order count',
  },
  {
    id: '34',
    title: 'Pending',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Pending purchase order count',
  },
  {
    id: '35',
    title: 'Received',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '6',
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.PURCHASE_ORDER,
    description: 'Received purchase order count',
  },

  {
    id: '36',
    title: 'Forecast Analytics',
    chartType: CHARTS?.HORIZONTAL_BAR_CHART,
    type: CHARTS?.TEMPLATE_HORIZONTAL_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '37',
    title: 'Over Time',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '38',
    title: 'Comparison',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '39',
    title: 'Overview',
    tableColumns: ['salesPipelineId', 'users', 'goalStatus', 'target'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'salesPipelineId',
        collectionName: COLLECTION_NAME?.SALES_PIPELINES,
      },
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'users',
        collectionName: COLLECTION_NAME?.USERS,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'goalStatus',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'target',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.FORECAST,
    description: 'General Table',
  },
  {
    id: '40',
    title: 'Deals Analytics',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.DEALS,
    description: 'Visualize your data',
  },
  {
    id: '41',
    title: 'Deals Analytics',
    chartType: CHARTS?.PIE_CHART,
    type: CHARTS?.TEMPLATE_PIE_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.DEALS,
    description: 'Visualize your data',
  },
  {
    id: '42',
    title: 'Deals Overview',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['dealPipelineId', 'priority', 'billingFrequency'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'dealPipelineId',
        collectionName: COLLECTION_NAME?.DEAL_PIPELINES,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'priority',
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'billingFrequency',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.DEALS,
    description: 'General Table',
  },
  {
    id: '43',
    title: 'Total',
    ticketCount: '6',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.DEALS,
    description: 'Total deals count',
  },
  {
    id: '44',
    title: 'Open',
    ticketCount: '3',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.DEALS,
    description: 'Open deals count',
  },
  {
    id: '45',
    title: 'Close',
    ticketCount: '3',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    match: REPORT_TYPE?.COUNTER,
    templateType: REPORT_TYPE?.DEALS,
    description: 'Close deals count',
  },
  {
    id: '46',
    title: 'Forecast Analytics',
    chartType: CHARTS?.HORIZONTAL_BAR_CHART,
    type: CHARTS?.TEMPLATE_HORIZONTAL_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '47',
    title: 'Over Time',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '48',
    title: 'Comparison',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Priority', value: 'priority', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.FORECAST,
    description: 'Visualize your data',
  },
  {
    id: '49',
    title: 'Leads Geerated by CTA',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Status', value: 'status', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.LEADS,
    description: 'Visualize your data',
  },
  {
    id: '50',
    title: 'Table',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['campaignOwner', 'status'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'campaignOwner',
        collectionName: COLLECTION_NAME?.USERS,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs Table',
  },
  {
    id: '51',
    title: 'Form Views',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '68',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '52',
    title: 'CTA Rate',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '62%',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '53',
    title: 'Entraces',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '68',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '54',
    title: 'Average Time Per Page View',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '68',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '55',
    title: 'Total Submissions',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '156',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '56',
    title: 'CTA Clicks',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '06',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '57',
    title: 'CTA Views',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '42',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '58',
    title: 'Bounce Rate',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '40%',
    match: 'counter',
    templateType: REPORT_TYPE?.LEADS,
    description: 'LeadsCTAs',
  },
  {
    id: '59',
    title: 'Total Add Spend',
    chartType: CHARTS?.BAR_CHART,
    type: CHARTS?.TEMPLATE_BAR_CHART,
    xAxis: { label: 'Status', value: 'status', ref: null },
    subFilter: true,
    match: REPORT_TYPE?.CHART,
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'Visualize your data',
  },
  {
    id: '60',
    title: 'Ad Campaigns',
    type: REPORT_TYPE?.TEMPLATE_TABLE,
    tableColumns: ['campaignOwner', 'status'],
    templateColumnsData: [
      {
        fieldType: FIELD_TYPE?.OBJECT_ID,
        fieldName: 'campaignOwner',
        collectionName: COLLECTION_NAME?.USERS,
      },
      {
        fieldType: FIELD_TYPE?.STRING,
        fieldName: 'status',
      },
    ],
    match: 'table',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'General Table',
  },
  {
    id: '61',
    title: 'Impressions',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '4k',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'AdCampaigns',
  },
  {
    id: '62',
    title: 'Amount Spend',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '$20',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'AdCampaigns',
  },
  {
    id: '63',
    title: 'Clicks',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '93',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'AdCampaigns',
  },
  {
    id: '64',
    title: 'ROI',
    type: REPORT_TYPE?.TEMPLATE_TEXT,
    ticketCount: '50%',
    match: 'counter',
    templateType: REPORT_TYPE?.CAMPAIGNS,
    description: 'AdCampaigns',
  },
];

export const modalInitialState: any = {
  chart: false,
  text: false,
  table: false,
  counter: false,
};

export const mainMetrics = (setMetricType: any) => {
  return {
    [GENERIC_REPORT_MODULES?.SERVICES]: [
      {
        title: REPORT_TYPE?.INVENTORIES,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.INVENTORIES);
          closeMenu?.();
        },
      },
      {
        title: REPORT_TYPE?.SOFTWARE,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.SOFTWARE);
          closeMenu?.();
        },
      },
      {
        title: REPORT_TYPE?.CONTRACTS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.CONTRACTS);
          closeMenu?.();
        },
      },
      {
        title: REPORT_TYPE?.TICKETS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.TICKETS);
          closeMenu?.();
        },
      },
      {
        title: REPORT_TYPE?.PURCHASE_ORDER,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.PURCHASE_ORDER);
          closeMenu?.();
        },
      },
    ],
    [GENERIC_REPORT_MODULES?.SALES]: [
      {
        title: REPORT_TYPE?.DEALS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.DEALS);
          closeMenu?.();
        },
      },
      {
        title: REPORT_TYPE?.FORECAST,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.FORECAST);
          closeMenu?.();
        },
      },
    ],
    [GENERIC_REPORT_MODULES?.MARKETING]: [
      {
        title: REPORT_TYPE?.LEADS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.LEADS);
          closeMenu?.();
        },
      },
      {
        title: REPORT_TYPE?.CAMPAIGNS,
        handleClick: (closeMenu: any) => {
          setMetricType(REPORT_TYPE?.CAMPAIGNS);
          closeMenu?.();
        },
      },
    ],
  };
};
