export const ticketViewBoardArray = [
  {
    id: 1,
    status: 'Open',
    ticketId: '#INC-3',
    ticketAppearance: 'New',
    ticketMessage: "What's wrong with my email?",
    priority: 'Low',
    time: '2020-04-02T08:02:17-05:00',
    profilePicture: 'Pic',
    department: 'IT',
  },
  {
    id: 2,
    status: 'Resolved',
    ticketId: '#INC-4',
    ticketMessage: "What's wrong with my email?",
    priority: 'Medium',
    time: '2020-04-02T08:02:17-05:00',
    profilePicture: 'Pic',
    department: 'FI',
  },
  {
    id: 3,
    status: 'Pending',
    ticketId: '#INC-5',
    ticketAppearance: 'Overdue',
    ticketMessage: "What's wrong with my email?",
    priority: 'High',
    time: '2020-04-02T08:02:17-05:00',
    profilePicture: 'Pic',
    department: 'HR',
  },
  {
    id: 4,
    status: 'Closed',
    ticketId: '#INC-6',
    ticketAppearance: 'Response Due',
    ticketMessage: "What's wrong with my email?",
    priority: 'Low',
    time: '2020-04-02T08:02:17-05:00',
    profilePicture: 'Pic',
    department: 'IT',
  },
  {
    id: 5,
    status: 'Closed',
    ticketId: '#INC-3',
    ticketMessage: "What's wrong with my email?",
    priority: 'Low',
    time: '2020-04-02T08:02:17-05:00',
    profilePicture: 'Pic',
    department: 'IT',
  },
];
