import {
  DYNAMIC_REPORTS_TYPES,
  LOYALTY_REWARDS_TYPE,
  LOYALTY_RULES_ATTRIBUTES,
  LOYALTY_SHOP_TYPE,
  LOYALTY_TIERS_REWARD_TYPE,
  LOYALTY_TRANSACTIONS_CHANNEL,
  LOYALTY_TRANSACTIONS_TYPE,
  MANAGE_ACCESS_TYPES,
  OPERATORS,
  RULES_AUDIENCE_TYPE,
  RULES_TIME_SPAN,
} from './strings';

export const ERROR_TIME = {
  NAN_HOUR_MIN: 'NaNh:NaNm',
};

export const LOYALTY_TRANSACTIONS_TYPE_MAPPED = {
  [LOYALTY_TRANSACTIONS_TYPE?.PHYSICAL_REWARD]: 'Physical reward',
  [LOYALTY_TRANSACTIONS_TYPE?.DIGITAL_REWARD]: 'Digital reward',
};

export const LOYALTY_TRANSACTIONS_CHANNEL_MAPPED = {
  [LOYALTY_TRANSACTIONS_CHANNEL?.BUSINESS_DASHBOARD]: 'Business dashboard',
};

export const LOYALTY_RULES_ATTRIBUTES_MAPPED = {
  [LOYALTY_RULES_ATTRIBUTES?.PURCHASE_AMOUNT]: 'Purchase amount',
  [LOYALTY_RULES_ATTRIBUTES?.ACCOUNT_CREATION]: 'Account creation',
  [LOYALTY_RULES_ATTRIBUTES?.PRODUCT_QTY]: 'Product Qty',
  [LOYALTY_RULES_ATTRIBUTES?.NO_OF_VISITS]: 'No of Visits',
  [LOYALTY_RULES_ATTRIBUTES?.BIRTHDAY]: 'Birthday',
  [LOYALTY_RULES_ATTRIBUTES?.FIRST_PURCHASE]: 'First purchase',
  [LOYALTY_RULES_ATTRIBUTES?.MONEY_OFF]: 'Money off',
  [LOYALTY_RULES_ATTRIBUTES?.FREE_SHIPPING]: 'Free shipping',
};

export const OPERATORS_MAPPED = {
  [OPERATORS?.LESS_THEN]: 'Less then',
  [OPERATORS?.GREATER_THAN]: 'Greater then',
  [OPERATORS?.EQUAL_TO]: 'Equal to',
  [OPERATORS?.LESS_THEN_OR_EQUAL_TO]: 'Less then or equal to',
  [OPERATORS?.GREATER_THEN_AND_EQUAL_TO]: 'Greater then and equal to',
};

export const LOYALTY_SHOP_TYPE_MAPPED = {
  [LOYALTY_SHOP_TYPE?.ON_SITE]: 'On Site',
  [LOYALTY_SHOP_TYPE?.DEPARTMENT]: 'Department',
  [LOYALTY_SHOP_TYPE?.HEADQUARTERS]: 'Headquarters',
  [LOYALTY_SHOP_TYPE?.POINT_OF_SALE]: 'Point Of Sale',
  [LOYALTY_SHOP_TYPE?.WEB_SHOP]: 'Webshop',
};

export const LOYALTY_REWARDS_TYPE_MAPPED = {
  [LOYALTY_REWARDS_TYPE?.PHYSICAL_REWARD]: 'Physical reward',
  [LOYALTY_REWARDS_TYPE?.DIGITAL_REWARD]: 'Digital reward',
};

export const LOYALTY_TIERS_REWARD_TYPE_MAPPED = {
  [LOYALTY_TIERS_REWARD_TYPE?.FIXED_DISCOUNT]: 'Fixed',
  [LOYALTY_TIERS_REWARD_TYPE?.FLAT_DISCOUNT]: 'Percentage',
  [LOYALTY_TIERS_REWARD_TYPE?.POINTS]: 'Points',
};

export const RULES_TIME_SPAN_MAPPED = {
  [RULES_TIME_SPAN?.THIS_WEEK]: 'This week',
  [RULES_TIME_SPAN?.LAST_WEEK]: 'Last week',
  [RULES_TIME_SPAN?.THIS_MONTH]: 'This month',
  [RULES_TIME_SPAN?.LAST_MONTH]: 'Last month',
  [RULES_TIME_SPAN?.CUSTOM_DATE]: 'Custom Date',
};

export const RULES_AUDIENCE_TYPE_MAPPED = {
  [RULES_AUDIENCE_TYPE?.CUSTOMER]: 'Customer',
};

export const MANAGE_REPORTS_ACCESS_TYPES_MAPPED = {
  [MANAGE_ACCESS_TYPES?.PRIVATE_CAPITAL]: 'Private',
  [MANAGE_ACCESS_TYPES?.EVERYONE_CAPITAL]: 'Everyone',
  [MANAGE_ACCESS_TYPES?.SPECIFIC_USERS]: 'Specific users',
};

export const DYNAMIC_REPORTS_TYPES_MAPPED = {
  [DYNAMIC_REPORTS_TYPES?.CUSTOM]: 'Custom Report',
  [DYNAMIC_REPORTS_TYPES?.DASHBOARD]: 'Dashboard Report',
};
