import {
  LOYALTY_TRANSACTIONS_CHANNEL,
  LOYALTY_TRANSACTIONS_TYPE,
} from './strings';

export const ERROR_TIME = {
  NAN_HOUR_MIN: 'NaNh:NaNm',
};

export const LOYALTY_TRANSACTIONS_TYPE_MAPPED = {
  [LOYALTY_TRANSACTIONS_TYPE?.PHYSICAL_REWARD]: 'PHYSICAL REWARD',
  [LOYALTY_TRANSACTIONS_TYPE?.DIGITAL_REWARD]: 'DIGITAL REWARD',
};

export const LOYALTY_TRANSACTIONS_CHANNEL_MAPPED = {
  [LOYALTY_TRANSACTIONS_CHANNEL?.BUSINESS_DASHBOARD]: 'BUSINESS DASHBOARD',
};
