import {
  LOYALTY_REWARDS_TYPE,
  LOYALTY_RULES_ATTRIBUTES,
  LOYALTY_TRANSACTIONS_CHANNEL,
  LOYALTY_TRANSACTIONS_TYPE,
  OPERATORS,
} from './strings';

export const ERROR_TIME = {
  NAN_HOUR_MIN: 'NaNh:NaNm',
};

export const LOYALTY_TRANSACTIONS_TYPE_MAPPED = {
  [LOYALTY_TRANSACTIONS_TYPE?.PHYSICAL_REWARD]: 'Physical reward',
  [LOYALTY_TRANSACTIONS_TYPE?.DIGITAL_REWARD]: 'Digital reward',
};

export const LOYALTY_TRANSACTIONS_CHANNEL_MAPPED = {
  [LOYALTY_TRANSACTIONS_CHANNEL?.BUSINESS_DASHBOARD]: 'Business dashboard',
};

export const LOYALTY_RULES_ATTRIBUTES_MAPPED = {
  [LOYALTY_RULES_ATTRIBUTES?.PURCHASE_AMOUNT]: 'Purchase amount',
  [LOYALTY_RULES_ATTRIBUTES?.ACCOUNT_CREATION]: 'Account creation',
  [LOYALTY_RULES_ATTRIBUTES?.PRODUCT_QTY]: 'Product Qty',
  [LOYALTY_RULES_ATTRIBUTES?.NO_OF_VISITS]: 'No of Visits',
  [LOYALTY_RULES_ATTRIBUTES?.BIRTHDAY]: 'Birthday',
  [LOYALTY_RULES_ATTRIBUTES?.FIRST_PURCHASE]: 'First purchase',
  [LOYALTY_RULES_ATTRIBUTES?.MONEY_OFF]: 'Money off',
  [LOYALTY_RULES_ATTRIBUTES?.FREE_SHIPPING]: 'Free shipping',
};

export const OPERATORS_MAPPED = {
  [OPERATORS?.LESS_THEN]: 'Less then',
  [OPERATORS?.GREATER_THAN]: 'Greater then',
  [OPERATORS?.EQUAL_TO]: 'Equal to',
  [OPERATORS?.LESS_THEN_OR_EQUAL_TO]: 'Less then or equal to',
  [OPERATORS?.GREATER_THEN_AND_EQUAL_TO]: 'Greater then and equal to',
};

export const LOYALTY_REWARDS_TYPE_MAPPED = {
  [LOYALTY_REWARDS_TYPE?.PHYSICAL_REWARD]: 'Physical reward',
  [LOYALTY_REWARDS_TYPE?.DIGITAL_REWARD]: 'Digital reward',
};
