export const ROLE_AND_RIGHTS_STATUS = {
  ACTIVE: 'ACTIVE',
  IN_ACTIVE: 'IN_ACTIVE',
};

export const LOYALTY_PROGRAM_RULE_STATUS = {
  ACTIVE: 'ACTIVE',
  IN_ACTIVE: 'INACTIVE',
};

export const LOYALTY_PROGRAM_TIERS_REWARD_TYPE = {
  FIXED_DISCOUNT: 'FIXED_DISCOUNT',
  FLAT_DISCOUNT: 'FLAT_DISCOUNT',
  POINTS: 'POINTS',
};

export const LOYALTY_PROGRAM_RULES_BENEFIT_TYPE = {
  DISCOUNT: 'DISCOUNT',
  AWARD: 'AWARD',
};

export const LOYALTY_PROGRAM_RULES_TIME_SPAN = {
  THIS_WEEK: 'THIS_WEEK',
  LAST_WEEK: 'LAST_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  LAST_MONTH: 'LAST_MONTH',
  CUSTOM_DATE: 'CUSTOM_DATE',
};
