import {
  AIR_SALES_DEALS_PERMISSIONS,
  SUPER_ADMIN_BILLING_INVOICES_PERMISSIONS,
  SUPER_ADMIN_DASHBOARD_PERMISSIONS,
  SUPER_ADMIN_PLAN_MANAGEMENT_PERMISSIONS,
  SUPER_ADMIN_USER_MANAGEMENT_PERMISSIONS,
} from './permission-keys';

export const Permissions = {
  view_dashoard: [SUPER_ADMIN_DASHBOARD_PERMISSIONS.VIEW_DASHBOARD],
  user_management: [
    SUPER_ADMIN_USER_MANAGEMENT_PERMISSIONS.USER_LIST,
    SUPER_ADMIN_USER_MANAGEMENT_PERMISSIONS.ADD_USER,
    SUPER_ADMIN_USER_MANAGEMENT_PERMISSIONS.USER_SEARCH_AND_FILTER,
    SUPER_ADMIN_USER_MANAGEMENT_PERMISSIONS.PLAN_MANAGEMENT,
  ],
  PLAN_MANAGEMENT: [SUPER_ADMIN_PLAN_MANAGEMENT_PERMISSIONS.PLAN_LIST],
  BILLING_AND_INVOICES: [
    SUPER_ADMIN_BILLING_INVOICES_PERMISSIONS.BILLING_INVOICES_LIST,
    SUPER_ADMIN_BILLING_INVOICES_PERMISSIONS.BILLING_SEARCH_AND_FILTER,
    SUPER_ADMIN_BILLING_INVOICES_PERMISSIONS.ASSIGN_PLAN,
    SUPER_ADMIN_BILLING_INVOICES_PERMISSIONS.BILLING_EDIT_PLAN,
    SUPER_ADMIN_BILLING_INVOICES_PERMISSIONS.VIEW_BILLING_DETAILS,
  ],
  AIR_SALES_DEALS: [
    AIR_SALES_DEALS_PERMISSIONS?.UPDATE_INFO,
    AIR_SALES_DEALS_PERMISSIONS?.VIEW_ACTIVITY_LOG,
    AIR_SALES_DEALS_PERMISSIONS?.ADD_ASSOCIATE_CONTACTS,
    AIR_SALES_DEALS_PERMISSIONS?.EDIT_CONTACTS,
    AIR_SALES_DEALS_PERMISSIONS?.VIEW_CONTACTS,
    AIR_SALES_DEALS_PERMISSIONS?.REMOVE_CONTACTS,
    AIR_SALES_DEALS_PERMISSIONS?.ADD_ASSOCIATE_TICKETS,
    AIR_SALES_DEALS_PERMISSIONS?.EDIT_TICKETS,
    AIR_SALES_DEALS_PERMISSIONS?.VIEW_TICKETS,
    AIR_SALES_DEALS_PERMISSIONS?.REMOVE_TICKETS,
    AIR_SALES_DEALS_PERMISSIONS?.ADD_ASSOCIATE_COMPANIES,
    AIR_SALES_DEALS_PERMISSIONS?.EDIT_COMPANIES,
    AIR_SALES_DEALS_PERMISSIONS?.VIEW_COMPANIES,
    AIR_SALES_DEALS_PERMISSIONS?.REMOVE_COMPANIES,
    AIR_SALES_DEALS_PERMISSIONS?.ADD_ASSOCIATE_PRODUCTS,
    AIR_SALES_DEALS_PERMISSIONS?.EDIT_PRODUCTS,
  ],
};
