export const AIR_SERVICES = {
  DASHBOARD: `/air-services`,
  SINGLE_DASHBOARD: `/air-services/dashboard`,
  TICKETS: `/air-services/tickets`,
  TICKETS_LIST: `/air-services/tickets/detail`,
  CHILD_TICKETS_DETAIL: `/air-services/tickets/child-detail`,
  PURCHASE_ORDER: '/air-services/assets/purchase-orders',
  ASSETS_PURCHASE_ORDER_DETAIL: '/air-services/assets/purchase-orders/detail',
  NEW_PURCHASE_ORDER: '/air-services/assets/purchase-orders/new-purchase',
  CREATE_DASHBOARD: '/air-services/dashboard/upsert-dashboard',
  MANAGE_DASHBOARD: '/air-services/dashboard/manage-dashboard',
  KNOWLEDGE_BASE: '/air-services/knowledge-base',
  KNOWLEDGE_BASE_VIEW_ARTICLE:
    '/air-services/knowledge-base/article/view-article',
  KNOWLEDGE_BASE_UPSERT_ARTICLE:
    '/air-services/knowledge-base/article/upsert-article',
  ADD_ASSOCIATE_ASSET:
    '/air-services/assets/contracts/detail/add-associate-asset',
  ASSETS_CONTRACTS: '/air-services/assets/contracts',
  ASSETS_CONTRACTS_DETAIL: '/air-services/assets/contracts/detail',
  UPSERT_CONTRACT: `/air-services/assets/contracts/upsert-contract`,
  UPDATE_CONTRACT: `/air-services/assets/contracts/detail/update-contract`,
  ASSETS_INVENTORY: `/air-services/assets/inventory`,
  ASSETS_INVENTORY_DETAIL: `/air-services/assets/inventory/detail`,
  ASSETS_SOFTWARE: `/air-services/assets/software`,
  ASSETS_SOFTWARE_DETAIL: `/air-services/assets/software/detail`,
  ADD_INVENTORY: `/air-services/assets/inventory/add-inventory`,
  UPSERT_ARTICLE: `/air-services/knowledge-base/article/upsert-article`,
  ACCOUNT_SETTINGS: `/air-services/settings/account-settings`,
  ACCOUNT_DETAILS_SETTINGS: `/air-services/settings/account-settings/account-details`,
  EMAIL_NOTIFICATION_SETTINGS: `/air-services/settings/account-settings/email-notification`,
  MANAGE_PORTAL_SETTINGS: `/air-services/settings/account-settings/manage-portal-settings`,
  ASSET_MANAGEMENT_SETTINGS: `/air-services/settings/asset-management`,
  ASSET_TYPE_SETTINGS: `/air-services/settings/asset-management/asset-type`,
  PRODUCT_CATALOG_SETTINGS: `/air-services/settings/asset-management/product-catalog`,
  VENDOR_SETTINGS: `/air-services/settings/asset-management/vendor`,
  VENDOR_FIELDS_SETTINGS: `/air-services/settings/asset-management/vendor-fields`,
  LOCATION_SETTINGS: `/air-services/settings/asset-management/location`,
  SERVICE_MANAGEMENT: `/air-services/settings/service-management`,
  SERVICE_CATALOG_SETTINGS: `/air-services/settings/service-management/services-catalog`,
  BUSINESS_HOURS_SETTINGS: `/air-services/settings/service-management/business-hours`,
  CLOSURE_RULE_SETTINGS: `/air-services/settings/service-management/closure-rule`,
  USER_MANAGEMENT: `/air-services/settings/user-management`,
  DEPARTMENT_SETTINGS: `/air-services/settings/user-management/departments`,
  AGENTS_SETTINGS: `/air-services/settings/user-management/agents`,
  REQUESTERS_SETTINGS: `/air-services/settings/user-management/requesters`,
  SINGLE_REQUESTERS_DETAILS: `/air-services/settings/user-management/requesters/requesters-view-details`,
  USER_ROLES_SETTINGS: `/air-services/settings/user-management/roles`,
  VENDOR_DETAIL: '/air-services/settings/asset-management/vendor/details',
  PRODUCT_CATALOG: `/air-services/settings/asset-management/product-catalog`,
  UPSERT_PRODUCT_CATALOG: `/air-services/settings/asset-management/product-catalog/upsert-product`,
  SINGLE_PRODUCT_CATALOG: `/air-services/settings/asset-management/product-catalog/details`,
  AGENT_PERFORMANCE_MANAGEMENT_SETTINGS: `/air-services/settings/agent-performance-management`,
  CANNED_RESPONSE_SETTINGS: `/air-services/settings/agent-performance-management/canned-responses`,
  LEADER_BOARD_SETTINGS: `/air-services/settings/agent-performance-management/leader-board`,
  WORKLOAD_MANAGEMENT_SETTINGS: `/air-services/settings/agent-performance-management/workload-management`,
  USER_UPSERT_ROLES_SETTINGS: `/air-services/settings/user-management/roles/upsert-roles`,
  UPSERT_BUSINESS_HOUR: `/air-services/settings/service-management/business-hours/upsert-business-hour`,
  ADD_NEW_LOCATION: `/air-services/settings/asset-management/location/upsert-location`,
  UPSERT_INVENTORY: `/air-services/assets/inventory/upsert-inventory`,
  UPSERT_SERVICE:
    '/air-services/settings/service-management/services-catalog/upsert-service',
  SERVICE_CATALOG: '/air-services/settings/service-management/services-catalog',
  UPSERT_SOFTWARE_CONTRACT: `/air-services/assets/software/detail/create-contract`,
  UPSERT_WORKFLOW_MANAGEMENT:
    '/air-services/settings/agent-performance-management/workload-management/upsert-workflow-management',
  SINGLE_AGENT_DETAILS: `/air-services/settings/user-management/agents/details`,
  REPORTS: `/air-services/reports`,
  INVENTORY_REPORTS: `/air-services/reports/inventory`,
  TICKETS_REPORTS: `/air-services/reports/tickets`,
  CONTRACTS_REPORTS: `/air-services/reports/contracts`,
  PURCHASE_ORDER_REPORTS: `/air-services/reports/purchase-order`,
  SOFTWARE_REPORTS: `/air-services/reports/software`,
  FEEDBACK_SURVEY: `/air-services/feedback-survey`,
  UPSERT_FEEDBACK_SURVEY: `/air-services/feedback-survey/upsert-feedback-survey`,
  FEEDBACK_SURVEY_RESPONSES: `/air-services/feedback-survey/detail`,
  DEPARTMENT_FIELD: `/air-services/settings/user-management/department-field`,
  AGENT_FIELDS: `/air-services/settings/user-management/agent-fields`,
  REQUESTER_FIELDS: `/air-services/settings/user-management/requester-fields`,
  SOFTWARE_FIELDS: `/air-services/settings/asset-management/software-fields`,
  CONTRACT_TYPES: `/air-services/settings/asset-management/contract-types`,
  PURCHASE_ORDER_FIELDS: `/air-services/settings/asset-management/purchase-order-fields`,
  FIELD_MANAGER: `/air-services/settings/service-management/field-manager`,
  TICKET_FIELDS: `/air-services/settings/service-management/field-manager/ticket-fields`,
  TASK_FIELDS: `/air-services/settings/service-management/field-manager/task-fields`,
  TIME_ENTRY_FIELDS: `/air-services/settings/service-management/field-manager/time-entry-fields`,
  ASSET_TYPE_DEFAULT_FIELDS: `/air-services/settings/asset-management/asset-type/default-fields`,
  ASSET_TYPE_CREATE_FIELDS: `/air-services/settings/asset-management/asset-type/create-fields`,
  CONTACT_TYPE_CREATE_FIELDS: `/air-services/settings/asset-management/contract-types/create-fields`,
  SERVICES_PUBLIC_DASHBOARD: `dynamic-dashboard/download`,
};

export const AIR_CUSTOMER_PORTAL = {
  DASHBOARD: `/air-customer-portal`,
  EDIT_PROFILE: `/air-customer-portal/edit-profile`,
  TICKETS: `/air-customer-portal/tickets`,
  SINGLE_TICKETS: `/air-customer-portal/tickets/single-ticket`,
  KNOWLEDGE_BASE: '/air-customer-portal/knowledge-base',
  KNOWLEDGE_BASE_DETAIL:
    '/air-customer-portal/knowledge-base/knowledge-base-detail',
  AIR_CUSTOMER_PORTAL_LOGIN: '/air-customer-portal/log-in',
  AIR_CUSTOMER_PORTAL_SIGN_UP: '/air-customer-portal/sign-up',
  CUSTOMER_PORTAL_VERIFICATION: '/air-customer-portal/verification',
  SINGLE_CATALOG_SERVICE_DETAILS: `/air-customer-portal/catalog/detail`,
  CATALOG_SERVICES: '/air-customer-portal/catalog',
  NON_REGISTER_DASHBOARD: '/air-customer-portal/non-register-dashboard',
  KNOWLEDGE_BASE_TICKET_DETAIL:
    '/air-customer-portal/knowledge-base/knowledge-base-detail/knowledge-base-ticket-detail',
  CUSTOMER_PORTAL_DASHBOARD: '/air-customer-portal',
  APPROVALS: '/air-customer-portal/catalog/approvals',
  APPROVALS_DETAIL: '/air-customer-portal/catalog/approvals/detail',
  UPSERT_SURVEY_RESPONSE: '/air-customer-portal/survey',
};

export const AIR_OPERATIONS = {
  DASHBOARD: '/air-operations',
  WORKFLOW_AUTOMATION: `/air-operations/workflow-automation`,
  SALES_WORKFLOW: `/air-operations/workflow-automation/sales-workflow`,
  UPSERT_SALES_WORKFLOW: `/air-operations/workflow-automation/sales-workflow/upsert-sales-workflow`,
  SERVICES_WORKFLOW: `/air-operations/workflow-automation/services-workflow`,
  MARKETING_WORKFLOW: `/air-operations/workflow-automation/marketing-workflow`,
  ROLES_AND_RIGHTS: `/air-operations/roles-and-right`,
  UPSERT_MARKETING_WORKFLOW: `/air-operations/workflow-automation/marketing-workflow/upsert-marketing-workflow`,
  UPSERT_SCHEDULE_WORKFLOW: `/air-operations/workflow-automation/services-workflow/upsert-schedule-workflow`,
  UPSERT_EVENT_BASED_WORKFLOW: `/air-operations/workflow-automation/services-workflow/upsert-event-based-workflow`,
  UPSERT_SUPERVISOR_RULES: `/air-operations/workflow-automation/services-workflow/upsert-supervisor-rules`,
  REPORTS: `/air-operations/reports`,
  REPORTS_LIST: `/air-operations/reports/reports-list`,
  RESTORE_REPORTS_LIST: `/air-operations/reports/restore-reports-list`,
  UPSERT_ROLES: '/air-operations/roles-and-right/upsert-roles-and-right',
  UPSERT_GENERIC_REPORTS: `/air-operations/reports/upsert-generic-reports`,
  SINGLE_GENERIC_REPORTS_DETAILS: `/air-operations/reports/single-report-view`,
};

export const AIR_LOYALTY_PROGRAM = {
  DASHBOARD: '/air-loyalty-program',
  REWARDS: `/air-loyalty-program/loyalty/rewards`,
  ADD_REWARDS: `/air-loyalty-program/loyalty/rewards/add-rewards`,
  GIFT_CARDS: `/air-loyalty-program/gift-cards/gift-cards`,
  VOUCHERS: `/air-loyalty-program/loyalty/vouchers`,
  VOUCHER_REDEMPTION_LIST: `/air-loyalty-program/loyalty/vouchers/voucher-redemptions-list`,
  GIFT_CARDS_DETAIL: `/air-loyalty-program/gift-cards/gift-cards/gift-cards-details`,
  TRANSACTIONS: '/air-loyalty-program/gift-cards/transactions',
  UPSERT_ROLES: '/air-loyalty-program/roles-and-right/upsert-roles-and-right',
  ROLES_AND_RIGHTS: '/air-loyalty-program/roles-and-right',
  CONSUMERS: '/air-loyalty-program/consumers',
  UPSERT_CONSUMER: '/air-loyalty-program/consumers/upsert-consumer',
};

export const SOCIAL_COMPONENTS = {
  COMPANIES: `/social-components/companies`,
  VIEW_COMPANY_DETAILS: '/social-components/companies/view-details',
  MEETINGS: '/social-components/meetings',
  MEETINGS_SETTINGS: '/social-components/meetings/settings',
  SCHEDULE_MEETING: '/social-components/meetings/schedule-meetings',
  UPSERT_MEETING:
    '/social-components/meetings/schedule-meetings/upsert-meeting',
  CALENDER_VIEW: '/social-components/meetings/calendar-view',
  CREATE_MEETING_TEMPLATE:
    '/social-components/meetings/schedule-meetings/upsert-meeting/email-template/create-email-template',
  EMAIL_TEMPLATE:
    '/social-components/meetings/schedule-meetings/upsert-meeting/email-template',
};

export const QUICK_LINKS = {
  CALLING: '/social-components/calling',
  DOCUMENT: '/social-components/documents',
  CHAT: '/social-components/chat',
  EMAIL: '/social-components/email',
  COMPANIES: '/social-components/companies',
  MEETINGS: '/social-components/meetings',
};
