export const timeZone = [
  {
    _id: 1,
    label: '(GMT+04:00) Perth',
    standardTimeZone: 'Morocco Standard Time',
    abb: 'MST',
  },
  {
    _id: 2,
    label: '(GMT) Coordinated Universal Time',
    standardTimeZone: 'Coordinated Universal Time',
    abb: 'CUT',
  },
  {
    _id: 3,
    label: '(GMT) Dublin, Edinburgh, Lisbon, London',
    standardTimeZone: 'GMT Standard Time',
    abb: 'GST',
  },
  {
    _id: 4,
    label: '(GMT) Monrovia, Reykjavik',
    standardTimeZone: 'Greenwich Standard Time',
    abb: 'GST',
  },
  {
    _id: 5,
    label: '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    standardTimeZone: 'W. Europe Standard Time',
    abb: 'WEST',
  },
  {
    _id: 6,
    label: '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    standardTimeZone: 'Central Europe Standard Time',
    abb: 'CEST',
  },
  {
    _id: 7,
    label: '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',
    standardTimeZone: 'Romance Standard Time',
    abb: 'RST',
  },
  {
    _id: 8,
    label: '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    standardTimeZone: 'Central European Standard Time',
    abb: 'CEST',
  },
  {
    _id: 9,
    label: '(GMT+01:00) West Central Africa',
    standardTimeZone: 'W. Central Africa Standard Time',
    abb: 'WCAST',
  },
  {
    _id: 10,
    label: '(GMT+01:00) Windhoek',
    standardTimeZone: 'Namibia Standard Time',
    abb: 'NST',
  },
  {
    _id: 11,
    label: '(GMT+02:00) Amman',
    standardTimeZone: 'Jordan Standard Time',
    abb: 'JST',
  },
  {
    _id: 12,
    label: '(GMT+02:00) Athens, Bucharest',
    standardTimeZone: 'GTB Standard Time',
    abb: 'GST',
  },
  {
    _id: 13,
    label: '(GMT+02:00) Beirut',
    standardTimeZone: 'Middle East Standard Time',
    abb: 'MEST',
  },
  {
    _id: 14,
    label: '(GMT+02:00) Cairo',
    standardTimeZone: 'Egypt Standard Time',
    abb: 'EST',
  },
  {
    _id: 15,
    label: '(GMT+02:00) Damascus',
    standardTimeZone: 'Syria Standard Time',
    abb: 'SST',
  },
  {
    _id: 16,
    label: '(GMT+02:00) Harare, Pretoria',
    standardTimeZone: 'South Africa Standard Time',
    abb: 'SAST',
  },
  {
    _id: 17,
    label: '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    standardTimeZone: 'FLE Standard Time',
    abb: 'FST',
  },
  {
    _id: 18,
    label: '(GMT+02:00) Istanbul',
    standardTimeZone: 'Turkey Standard Time',
    abb: 'TST',
  },
  {
    _id: 19,
    label: '(GMT+02:00) Jerusalem',
    standardTimeZone: 'Jerusalem Standard Time',
    abb: 'JST',
  },
  {
    _id: 20,
    label: '(GMT+02:00) Nicosia',
    standardTimeZone: 'E. Europe Standard Time',
    abb: 'EEST',
  },
  {
    _id: 21,
    label: '(GMT+02:00) Baghdad',
    standardTimeZone: 'Arabic Standard Time',
    abb: 'AST',
  },
  {
    _id: 22,
    label: '(GMT+03:00) Kaliningrad, Minsk',
    standardTimeZone: 'Kaliningrad Standard Time',
    abb: 'KST',
  },
  {
    _id: 23,
    label: '(GMT+03:00) Kuwait, Riyadh',
    standardTimeZone: 'Arab Standard Time',
    abb: 'AST',
  },
  {
    _id: 24,
    label: '(GMT+03:00) Nairobi',
    standardTimeZone: 'E. Africa Standard Time',
    abb: 'EAST',
  },
  {
    _id: 25,
    label: '(GMT+03:30) Tehran',
    standardTimeZone: 'Iran Standard Time',
    abb: 'IST',
  },
  {
    _id: 26,
    label: '(GMT+04:00) Abu Dhabi, Muscat',
    standardTimeZone: 'Arabian Standard Time',
    abb: 'AST',
  },
  {
    _id: 27,
    label: '(GMT+04:00) Baku',
    standardTimeZone: 'Azerbaijan Standard Time',
    abb: 'AST',
  },
  {
    _id: 28,
    label: '(GMT+04:00) Moscow, St. Petersburg, Volgograd',
    standardTimeZone: 'Russian Standard Time',
    abb: 'RST',
  },
  {
    _id: 29,
    label: '(GMT+04:00) Port Louis',
    standardTimeZone: 'Mauritius Standard Time',
    abb: 'MST',
  },
  {
    _id: 30,
    label: '(GMT+04:00) Tbilisi',
    standardTimeZone: 'Georgian Standard Time',
    abb: 'GST',
  },
  {
    _id: 31,
    label: '(GMT+04:00) Yerevan',
    standardTimeZone: 'Caucasus Standard Time',
    abb: 'CST',
  },
  {
    _id: 32,
    label: '(GMT+04:30) Kabul',
    standardTimeZone: 'Afghanistan Standard Time',
    abb: 'AST',
  },
  {
    _id: 33,
    label: '(GMT+05:00) Islamabad, Karachi',
    standardTimeZone: 'Pakistan Standard Time',
    abb: 'PST',
  },
  {
    _id: 34,
    label: '(GMT+05:00) Tashkent',
    standardTimeZone: 'West Asia Standard Time',
    abb: 'WAST',
  },
  {
    _id: 35,
    label: '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    standardTimeZone: 'India Standard Time',
    abb: 'IST',
  },
  {
    _id: 36,
    label: '(GMT+05:30) Sri Jayawardenepura',
    standardTimeZone: 'Sri Lanka Standard Time',
    abb: 'SLST',
  },
  {
    _id: 37,
    label: '(GMT+05:45) Kathmandu',
    standardTimeZone: 'Nepal Standard Time',
    abb: 'NST',
  },
  {
    _id: 38,
    label: '(GMT+06:00) Astana',
    standardTimeZone: 'Central Asia Standard Time',
    abb: 'CAST',
  },
  {
    _id: 39,
    label: '(GMT+06:00) Dhaka',
    standardTimeZone: 'Bangladesh Standard Time',
    abb: 'BST',
  },
  {
    _id: 40,
    label: '(GMT+06:00) Ekaterinburg',
    standardTimeZone: 'Ekaterinburg Standard Time',
    abb: 'EST',
  },
  {
    _id: 41,
    label: '(GMT+06:30) Yangon (Rangoon)',
    standardTimeZone: 'Myanmar Standard Time',
    abb: 'MST',
  },
  {
    _id: 42,
    label: '(GMT+07:00) Bangkok, Hanoi, Jakarta',
    standardTimeZone: 'SE Asia Standard Time',
    abb: 'SAST',
  },
  {
    _id: 43,
    label: '(GMT+07:00) Novosibirsk',
    standardTimeZone: 'N. Central Asia Standard Time',
    abb: 'NCAST',
  },
  {
    _id: 44,
    label: '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    standardTimeZone: 'China Standard Time',
    abb: 'CST',
  },
  {
    _id: 45,
    label: '(GMT+08:00) Krasnoyarsk',
    standardTimeZone: 'North Asia Standard Time',
    abb: 'NAST',
  },
  {
    _id: 46,
    label: '(GMT+08:00) Kuala Lumpur, Singapore',
    standardTimeZone: 'Malay Peninsula Standard Time',
    abb: 'MPST',
  },
  {
    _id: 47,
    label: '(GMT+08:00) Perth',
    standardTimeZone: 'W. Australia Standard Time',
    abb: 'WAST',
  },
  {
    _id: 48,
    label: '(GMT+08:00) Taipei',
    standardTimeZone: 'Taipei Standard Time',
    abb: 'TST',
  },
  {
    _id: 49,
    label: '(GMT+08:00) Ulaanbaatar',
    standardTimeZone: 'Ulaanbaatar Standard Time',
    abb: 'UST',
  },
  {
    _id: 50,
    label: '(GMT+09:00) Irkutsk',
    standardTimeZone: 'North Asia East Standard Time',
    abb: 'NAEST',
  },
  {
    _id: 51,
    label: '(GMT+09:00) Osaka, Sapporo, Tokyo',
    standardTimeZone: 'Tokyo Standard Time',
    abb: 'TST',
  },
  {
    _id: 52,
    label: '(GMT+09:00) Seoul',
    standardTimeZone: 'Korea Standard Time',
    abb: 'KST',
  },
  {
    _id: 53,
    label: '(GMT+09:30) Adelaide',
    standardTimeZone: 'Cen. Australia Standard Time',
    abb: 'CAST',
  },
  {
    _id: 54,
    label: '(GMT+09:30) Darwin',
    standardTimeZone: 'AUS Central Standard Time',
    abb: 'ACST',
  },
  {
    _id: 55,
    label: '(GMT+10:00) Brisbane',
    standardTimeZone: 'E. Australia Standard Time',
    abb: 'EAST',
  },
  {
    _id: 56,
    label: '(GMT+10:00) Canberra, Melbourne, Sydney',
    standardTimeZone: 'AUS Eastern Standard Time',
    abb: 'AEST',
  },
  {
    _id: 57,
    label: '(GMT+10:00) Guam, Port Moresby',
    standardTimeZone: 'West Pacific Standard Time',
    abb: 'WPST',
  },
  {
    _id: 58,
    label: '(GMT+10:00) Hobart',
    standardTimeZone: 'Tasmania Standard Time',
    abb: 'TST',
  },
  {
    _id: 59,
    label: '(GMT+10:00) Yakutsk',
    standardTimeZone: 'Yakutsk Standard Time',
    abb: 'YST',
  },
  {
    _id: 60,
    label: '(GMT+11:00) Solomon Is., New Caledonia',
    standardTimeZone: 'Central Pacific Standard Time',
    abb: 'CPST',
  },
  {
    _id: 61,
    label: '(GMT+11:00) Vladivostok',
    standardTimeZone: 'Vladivostok Standard Time',
    abb: 'VST',
  },
  {
    _id: 62,
    label: '(GMT+12:00) Auckland, Wellington',
    standardTimeZone: 'New Zealand Standard Time',
    abb: 'NZST',
  },
  {
    _id: 63,
    label: '(GMT+12:00) Coordinated Universal Time+12',
    standardTimeZone: 'GMT+12',
    abb: 'U',
  },
  {
    _id: 64,
    label: '(GMT+12:00) Fiji',
    standardTimeZone: 'Fiji Standard Time',
    abb: 'FST',
  },
  {
    _id: 65,
    label: '(GMT+12:00) Magadan',
    standardTimeZone: 'Magadan Standard Time',
    abb: 'MST',
  },
  {
    _id: 66,
    label: '(GMT+12:00) Petropavlovsk-Kamchatsky - Old',
    standardTimeZone: 'Kamchatka Standard Time',
    abb: 'KST',
  },
  {
    _id: 67,
    label: "(GMT+13:00) Nuku'alofa",
    standardTimeZone: 'Tonga Standard Time',
    abb: 'TST',
  },
  {
    _id: 68,
    label: '(GMT+13:00) Samoa',
    standardTimeZone: 'Samoa Standard Time',
    abb: 'SST',
  },
  {
    _id: 69,
    label: '(GMT-01:00) Azores',
    standardTimeZone: 'Azores Standard Time',
    abb: 'AST',
  },
  {
    _id: 70,
    label: '(GMT-01:00) Cape Verde Is.',
    standardTimeZone: 'Cape Verde Standard Time',
    abb: 'CVST',
  },
  {
    _id: 71,
    label: '(GMT-02:00) Coordinated Universal Time-02',
    standardTimeZone: 'GMT-02',
    abb: 'U',
  },
  {
    _id: 72,
    label: '(GMT-02:00) Mid-Atlantic',
    standardTimeZone: 'Mid-Atlantic Standard Time',
    abb: 'MST',
  },
  {
    _id: 73,
    label: '(GMT-03:00) Brasilia',
    standardTimeZone: 'E. South America Standard Time',
    abb: 'ESAST',
  },
  {
    _id: 74,
    label: '(GMT-03:00) Buenos Aires',
    standardTimeZone: 'Argentina Standard Time',
    abb: 'AST',
  },
  {
    _id: 75,
    label: '(GMT-03:00) Cayenne, Fortaleza',
    standardTimeZone: 'SA Eastern Standard Time',
    abb: 'SEST',
  },
  {
    _id: 76,
    label: '(GMT-03:00) Greenland',
    standardTimeZone: 'Greenland Standard Time',
    abb: 'GST',
  },
  {
    _id: 77,
    label: '(GMT-03:00) Montevideo',
    standardTimeZone: 'Montevideo Standard Time',
    abb: 'MST',
  },
  {
    _id: 78,
    label: '(GMT-03:00) Salvador',
    standardTimeZone: 'Bahia Standard Time',
    abb: 'BST',
  },
  {
    _id: 79,
    label: '(GMT-03:30) Newfoundland',
    standardTimeZone: 'Newfoundland Standard Time',
    abb: 'NST',
  },
  {
    _id: 80,
    label: '(GMT-04:00) Asuncion',
    standardTimeZone: 'Paraguay Standard Time',
    abb: 'PST',
  },
  {
    _id: 81,
    label: '(GMT-04:00) Atlantic Time (Canada)',
    standardTimeZone: 'Atlantic Standard Time',
    abb: 'AST',
  },
  {
    _id: 82,
    label: '(GMT-04:00) Cuiaba',
    standardTimeZone: 'Central Brazilian Standard Time',
    abb: 'CBST',
  },
  {
    _id: 83,
    label: '(GMT-04:00) Georgetown, La Paz, Manaus, San Juan',
    standardTimeZone: 'SA Western Standard Time',
    abb: 'SWST',
  },
  {
    _id: 84,
    label: '(GMT-04:00) Santiago',
    standardTimeZone: 'Pacific SA Standard Time',
    abb: 'PSST',
  },
  {
    _id: 85,
    label: '(GMT-04:30) Caracas',
    standardTimeZone: 'Venezuela Standard Time',
    abb: 'VST',
  },
  {
    _id: 86,
    label: '(GMT-05:00) Bogota, Lima, Quito',
    standardTimeZone: 'SA Pacific Standard Time',
    abb: 'SPST',
  },
  {
    _id: 87,
    label: '(GMT-05:00) Eastern Time (US & Canada)',
    standardTimeZone: 'Eastern Standard Time',
    abb: 'EST',
  },
  {
    _id: 88,
    label: '(GMT-05:00) Indiana (East)',
    standardTimeZone: 'US Eastern Standard Time',
    abb: 'UEST',
  },
  {
    _id: 89,
    label: '(GMT-06:00) Central America',
    standardTimeZone: 'Central America Standard Time',
    abb: 'CAST',
  },
  {
    _id: 90,
    label: '(GMT-06:00) Central Time (US & Canada)',
    standardTimeZone: 'Central Standard Time',
    abb: 'CST',
  },
  {
    _id: 91,
    label: '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
    standardTimeZone: 'Central Standard Time (Mexico)',
    abb: 'CST',
  },
  {
    _id: 92,
    label: '(GMT-06:00) Saskatchewan',
    standardTimeZone: 'Canada Central Standard Time',
    abb: 'CCST',
  },
  {
    _id: 93,
    label: '(GMT-07:00) Arizona',
    standardTimeZone: 'US Mountain Standard Time',
    abb: 'UMST',
  },
  {
    _id: 94,
    label: '(GMT-07:00) Chihuahua, La Paz, Mazatlan',
    standardTimeZone: 'Mountain Standard Time (Mexico)',
    abb: 'MST',
  },
  {
    _id: 95,
    label: '(GMT-07:00) Mountain Time (US & Canada)',
    standardTimeZone: 'Mountain Standard Time',
    abb: 'MST',
  },
  {
    _id: 96,
    label: '(GMT-08:00) Baja California',
    standardTimeZone: 'Pacific Standard Time (Mexico)',
    abb: 'PST',
  },
  {
    _id: 97,
    label: '(GMT-08:00) Pacific Time (US & Canada)',
    standardTimeZone: 'Pacific Standard Time',
    abb: 'PST',
  },
  {
    _id: 98,
    label: '(GMT-09:00) Alaska',
    standardTimeZone: 'Alaskan Standard Time',
    abb: 'AST',
  },
  {
    _id: 99,
    label: '(GMT-10:00) Hawaii',
    standardTimeZone: 'Hawaiian Standard Time',
    abb: 'HST',
  },
  {
    _id: 100,
    label: '(GMT-11:00) Coordinated Universal Time-11',
    standardTimeZone: 'GMT-11',
    abb: 'U',
  },
  {
    _id: 101,
    label: '(GMT-12:00) International Date Line West',
    standardTimeZone: 'Dateline Standard Time',
    abb: 'DST',
  },
];
