export const REGEX = {
  ALPHABETS_AND_SPACE: /^(?=.*[a-zA-Z])[a-zA-Z0-9\s]+$/,
};

export const CHARACTERS_LIMIT = {
  LOYALTY_REWARDS_TITLE_MAX_CHARACTERS: 30,
  LOYALTY_RULES_DESCRIPTION_MAX_CHARACTERS: 100,
  LOYALTY_RULES_ATTRIBUTES_MAX_CHARACTERS: 9999999999,
  LOYALTY_RULES_REWARDS_MAX_CHARACTERS: 9999999999,
  LOYALTY_RULES_REWARDS_MIN_CHARACTERS: 1,
  SERVICES_ENQUIRIES_VIEW_REPLY_MAX_CHARACTERS: 1000,
  SERVICES_ACCOUNT_SETTINGS_ACCOUNT_DETAILS_PROFILE_FIRST_NAME_MAX_CHARACTERS: 30,
  SERVICES_ACCOUNT_SETTINGS_ACCOUNT_DETAILS_PROFILE_LAST_NAME_MAX_CHARACTERS: 30,
  SERVICES_ACCOUNT_SETTINGS_ACCOUNT_DETAILS_PROFILE_JOB_TITLE_MAX_CHARACTERS: 30,
  SERVICES_ACCOUNT_SETTINGS_ACCOUNT_DETAILS_CHANGE_PASSWORD: 30,
  SERVICES_DASHBOARD_NAME_MAX_CHARACTERS: 100,
  SERVICES_DASHBOARD_ANNOUNCEMENT_TITLE_MAX_CHARACTERS: 30,
  SERVICES_DASHBOARD_ANNOUNCEMENT_DESCRIPTION_MAX_CHARACTERS: 100,
  SERVICES_TICKETS_SUBJECT_MAX_CHARACTERS: 50,
  SERVICES_TICKETS_DESCRIPTION_MAX_CHARACTERS: 1000,
  SERVICES_TICKETS_TASKS_TITLE_MAX_CHARACTERS: 50,
  SERVICES_TICKETS_TASKS_DESCRIPTION_MAX_CHARACTERS: 1000,
  SERVICES_TICKETS_TIME_NOTE_MAX_CHARACTERS: 500,
  SERVICES_TICKETS_APPROVALS_DESCRIPTION_MAX_CHARACTERS: 500,
  SERVICES_KNOWLEDGE_BASE_ARTICLES_TITLE_MAX_CHARACTERS: 50,
  SERVICES_KNOWLEDGE_BASE_ARTICLES_DESCRIPTION_MAX_CHARACTERS: 1000,
  SERVICES_KNOWLEDGE_BASE_FOLDER_NAME_MAX_CHARACTERS: 50,
  SERVICES_KNOWLEDGE_BASE_FOLDER_DESCRIPTION_MAX_CHARACTERS: 500,
  OPERATIONS_REPORTS_NAME_MAX_CHARACTERS: 50,
};

export const GLOBAL_CHARACTERS_LIMIT = {
  EMAIL: 100,
  NAME: 30,
  ADDRESS: 100,
  DESCRIPTION: 1000,
  DEFAULT: 50,
  SUBJECT: 100,
  EMAIL_SUBJECT: 100,
  EMAIL_DESCRIPTION: 1000,
};
