export const REGEX = {
  ALPHABETS_AND_SPACE: /^(?=.*[a-zA-Z])[a-zA-Z0-9\s]+$/,
};

export const CHARACTERS_LIMIT = {
  LOYALTY_REWARDS_TITLE_MAX_CHARACTERS: 30,
  LOYALTY_RULES_DESCRIPTION_MAX_CHARACTERS: 100,
  LOYALTY_RULES_ATTRIBUTES_MAX_CHARACTERS: 9999999999,
  LOYALTY_RULES_REWARDS_MAX_CHARACTERS: 9999999999,
};

export const GLOBAL_CHARACTERS_LIMIT = {
  EMAIL: 100,
  NAME: 30,
  ADDRESS: 100,
  DESCRIPTION: 1000,
  DEFAULT: 50,
};
