import { REPORT_TYPE } from '@/constants/strings';

export const defaultValues = () => {
  return {
    chartTitle: 'Report Chart',
    tableTitle: 'Report Table',
    textTitle: 'Report Text',
    xAxis: null,
  };
};

export const fieldsList = [
  {
    id: '0',
    title: 'Chart',
    match: 'chart',
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Text',
    match: 'text',
    description: 'Add context to your report',
  },
  {
    id: '2',
    title: 'Table',
    match: 'table',
    description: 'General Table',
  },
];

export const templateList = [
  {
    id: '0',
    title: 'Forecast Analytics',
    type: 'Horizontal Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Forecast_Category',
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Over Time',
    type: 'Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Forecast_Category',
    description: 'Visualize your data',
  },
  {
    id: '2',
    title: 'Comparison',
    type: 'Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Forecast_Category',
    description: 'Visualize your data',
  },
  {
    id: '3',
    title: 'Overview',
    tableColumns: [
      'Owner',
      'New',
      'Follow up',
      'Under review',
      'Demo',
      'Negotiation',
      'Won',
      'Total revenue goal',
    ],
    match: 'table',
    templateType: 'Forecast_Category',
    description: 'General Table',
  },
  {
    id: '4',
    title: 'Month Deal Stage',
    tableColumns: [
      'Name',
      '5/1/2023',
      '5/2/2023',
      '5/3/2023',
      '5/4/2023',
      '5/5/2023',
    ],
    match: 'table',
    templateType: 'Forecast_Category',
    description: 'General Table',
  },
  {
    id: '5',
    title: 'Year Deal Stage',
    tableColumns: [
      'Name',
      'Jan 2023',
      'Feb 2023',
      'March 2023',
      'April 2023',
      'May 2023',
    ],
    match: 'table',
    templateType: 'Forecast_Category',
    description: 'General Table',
  },
  {
    id: '6',
    title: 'Deals Analytics',
    type: 'Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Deals',
    description: 'Visualize your data',
  },
  {
    id: '7',
    title: 'Deals Analytics',
    type: 'Pie Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Tickets',
    subFilter: true,
    match: 'chart',
    templateType: 'Deals',
    description: 'Visualize your data',
  },
  {
    id: '8',
    title: 'Deals Overview',
    tableColumns: [
      'Deal Name',
      'Owner Channel',
      'Deal Pipeline Stage',
      'Deal Close Date',
      'Quote Name',
      'Amount',
      'Status',
    ],
    match: 'table',
    templateType: 'Deals',
    description: 'General Table',
  },
  {
    id: '9',
    title: 'Total Deals',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Deals',
    description: 'Deals',
  },
  {
    id: '10',
    title: 'Open Deals',
    ticketCount: '3',
    match: 'counter',
    templateType: 'Deals',
    description: 'Deals',
  },
  {
    id: '11',
    title: 'Close Deals',
    ticketCount: '3',
    match: 'counter',
    templateType: 'Deals',
    description: 'Deals',
  },
  {
    id: '12',
    title: 'Forecast Analytics',
    type: 'Horizontal Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Pipeline_Forecast',
    description: 'Visualize your data',
  },
  {
    id: '13',
    title: 'Over Time',
    type: 'Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Pipeline_Forecast',
    description: 'Visualize your data',
  },
  {
    id: '14',
    title: 'Comparison',
    type: 'Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Pipeline_Forecast',
    description: 'Visualize your data',
  },
  {
    id: '15',
    title: 'Overview',
    tableColumns: [
      'Owner',
      'New',
      'Follow up',
      'Under review',
      'Demo',
      'Negotiation',
      'Won',
      'Total revenue goal',
    ],
    match: 'table',
    templateType: 'Pipeline_Forecast',
    description: 'General Table',
  },
  {
    id: '16',
    title: 'Month Deal Stage',
    tableColumns: [
      'Name',
      '5/1/2023',
      '5/2/2023',
      '5/3/2023',
      '5/4/2023',
      '5/5/2023',
    ],
    match: 'table',
    templateType: 'Pipeline_Forecast',
    description: 'General Table',
  },
  {
    id: '17',
    title: 'Year Deal Stage',
    tableColumns: [
      'Name',
      'Jan 2023',
      'Feb 2023',
      'March 2023',
      'April 2023',
      'May 2023',
    ],
    match: 'table',
    templateType: 'Pipeline_Forecast',
    description: 'General Table',
  },
];

export const modalInitialState: any = {
  chart: false,
  text: false,
  table: false,
  counter: false,
};

export const salesMetrics = (setMetricType: any) => [
  {
    title: REPORT_TYPE?.DEALS,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.DEALS);
      closeMenu?.();
    },
  },
  {
    title: REPORT_TYPE?.PIPELINE_FORECAST,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.PIPELINE_FORECAST);
      closeMenu?.();
    },
  },
  {
    title: REPORT_TYPE?.FORECAST_CATEGORY,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.FORECAST_CATEGORY);
      closeMenu?.();
    },
  },
];
