import { AIR_OPERATIONS } from '@/constants';

const {
  SERVICES_REPORTS_RESTORE,
  MARKETING_REPORTS_RESTORE,
  SALES_REPORTS_RESTORE,
  SERVICES_REPORTS,
  SALES_REPORTS,
  MARKETING_REPORTS,
} = AIR_OPERATIONS;

export const REPORTS_BASE_MODULE: any = {
  [SERVICES_REPORTS_RESTORE]: SERVICES_REPORTS,
  [SALES_REPORTS_RESTORE]: SALES_REPORTS,
  [MARKETING_REPORTS_RESTORE]: MARKETING_REPORTS,
};
