export const columnsData = [
  { id: 'createdBy', title: 'Deal Owner' },
  { id: 'name', title: 'Deal Name' },
  // { id: '', 'title: 'Contacted Person' },
  // { id: '', 'title: 'Priority' },
  // { id: '', 'title: 'Assigned to' },
  // { id: '', 'title: 'Department' },
  // { id: '', 'title: 'Created Date' },
  // { id: '', 'title: 'Due Date' },
  { id: 'closeDate', title: 'Close Date' },
  { id: 'dealStage', title: 'Deal Stage' },
  { id: 'dealPipeline', title: 'Deal Pipeline' },
  { id: 'amount', title: 'Amount' },
  // { id: '', 'title: 'Products' },
];
