import {
  AIR_OPERATION_REPORTS_SALES_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_FAVOURITES_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_FAVOURITES_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_ALL_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_CUSTOM_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_DASHBOARD_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_FAVOURITES_PERMISSIONS,
  AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS,
  AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS,
  AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS,
} from '@/constants/permission-keys';
import { ReportLists } from '../ReportLists';
import { GENERIC_REPORT_MODULES } from '@/constants/strings';

const { SERVICES, SALES, MARKETING } = GENERIC_REPORT_MODULES ?? {};

export const PERMISSIONS_REPORTS = {
  [`${SERVICES}ALL`]: AIR_OPERATION_REPORTS_SERVICES_ALL_REPORTS_PERMISSIONS,
  [`${SERVICES}FAVOURITES`]:
    AIR_OPERATION_REPORTS_SERVICES_FAVOURITES_PERMISSIONS,
  [`${SERVICES}DASHBOARD`]:
    AIR_OPERATION_REPORTS_SERVICES_DASHBOARD_REPORTS_PERMISSIONS,
  [`${SERVICES}CUSTOM`]:
    AIR_OPERATION_REPORTS_SERVICES_CUSTOM_REPORTS_PERMISSIONS,
  [`${SALES}ALL`]: AIR_OPERATION_REPORTS_SALES_ALL_REPORTS_PERMISSIONS,
  [`${SALES}FAVOURITES`]: AIR_OPERATION_REPORTS_SALES_FAVOURITES_PERMISSIONS,
  [`${SALES}DASHBOARD`]:
    AIR_OPERATION_REPORTS_SALES_DASHBOARD_REPORTS_PERMISSIONS,
  [`${SALES}CUSTOM`]: AIR_OPERATION_REPORTS_SALES_CUSTOM_REPORTS_PERMISSIONS,
  [`${MARKETING}ALL`]: AIR_OPERATION_REPORTS_MARKETING_ALL_REPORTS_PERMISSIONS,
  [`${MARKETING}FAVOURITES`]:
    AIR_OPERATION_REPORTS_MARKETING_FAVOURITES_PERMISSIONS,
  [`${MARKETING}DASHBOARD`]:
    AIR_OPERATION_REPORTS_MARKETING_DASHBOARD_REPORTS_PERMISSIONS,
  [`${MARKETING}CUSTOM`]:
    AIR_OPERATION_REPORTS_MARKETING_CUSTOM_REPORTS_PERMISSIONS,
};

export const CREATE_REPORT_PERMISSIONS = {
  [SERVICES]: [
    AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
    AIR_OPERATION_REPORTS_SERVICES_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
  ],
  [SALES]: [
    AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
    AIR_OPERATION_REPORTS_SALES_CREATE_REPORT_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
  ],
  [MARKETING]: [
    AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_SCRATCH,
    AIR_OPERATION_REPORTS_MARKETING_CREATE_REPORTS_PERMISSIONS?.CREATE_REPORT_FROM_TEMPLATE,
  ],
};

export const moduleReportsListTabsDynamic = (
  canDisableTab: any,
  baseModule: string,
) => {
  return [
    {
      _id: 1,
      name: 'All Reports',
      id: 'allReports',
      tabPermissions: Object?.values(
        PERMISSIONS_REPORTS?.[`${baseModule}ALL`] ?? {},
      ),
      component: ReportLists,
      disabled: canDisableTab,
      componentProps: {},
    },
    {
      _id: 2,
      name: 'Favorite',
      id: 'favorite',
      tabPermissions: Object?.values(
        PERMISSIONS_REPORTS?.[`${baseModule}FAVOURITES`] ?? {},
      ),
      component: ReportLists,
      disabled: canDisableTab,
      componentProps: {},
    },
    {
      _id: 3,
      name: 'Dashboard Reports',
      id: 'dashboardReports',
      tabPermissions: Object?.values(
        PERMISSIONS_REPORTS?.[`${baseModule}DASHBOARD`] ?? {},
      ),
      component: ReportLists,
      disabled: canDisableTab,
      componentProps: {},
    },
    {
      _id: 4,
      name: 'Custom Reports',
      id: 'customReports',
      tabPermissions: Object?.values(
        PERMISSIONS_REPORTS?.[`${baseModule}CUSTOM`] ?? {},
      ),
      component: ReportLists,
      disabled: canDisableTab,
      componentProps: {},
    },
  ];
};
