import {
  FeedbackCompletionIcon,
  FeedbackDownIcon,
  FeedbackDropoutIcon,
  FeedbackStartIcon,
  FeedbackTimeOffIcon,
  FeedbackUpIcon,
  FeedbackViewIcon,
} from '@/assets/icons';

export const surveyWidgetsData: any = (data?: any, theme?: any) => [
  {
    id: 1,
    status: 'Viewed',
    rate: '175',
    hasSpinner: true,
    hasStatusIcon: false,
    statusIcon: '',
    rateIcon: FeedbackViewIcon,
    progress: '50',
    progressColor: theme?.palette?.primary?.dark,
  },
  {
    id: 2,
    status: 'Dropout',
    rate: '31',
    hasSpinner: true,
    hasStatusIcon: false,
    statusIcon: '',
    rateIcon: FeedbackDropoutIcon,
    progress: '60',
    progressColor: theme?.palette?.warning?.main,
  },
  {
    id: 3,
    status: 'Started',
    rate: '209',
    hasSpinner: true,
    hasStatusIcon: false,
    statusIcon: '',
    rateIcon: FeedbackStartIcon,
    progress: '80',
    progressColor: theme?.palette?.blue?.link_blue,
  },
  {
    id: 4,
    status: 'Completion rate',
    rate: '43%',
    hasSpinner: false,
    hasStatusIcon: true,
    statusIcon: FeedbackUpIcon,
    rateIcon: FeedbackCompletionIcon,
  },
  {
    id: 5,
    status: 'Average Time',
    rate: '2 mins',
    hasSpinner: false,
    hasStatusIcon: true,
    statusIcon: FeedbackDownIcon,
    rateIcon: FeedbackTimeOffIcon,
  },
];
