import { REPORT_TYPE } from '@/constants/strings';

export const fieldsList = [
  {
    id: '0',
    title: 'Chart',
    match: 'chart',
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Text',
    match: 'text',
    description: 'Add context to your report',
  },
  {
    id: '2',
    title: 'Table',
    match: 'table',
    description: 'General Table',
  },
];

export const templateList = [
  {
    id: '0',
    title: 'Tickets Analysis Report',
    type: 'Bar Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Users',
    subFilter: true,
    match: 'chart',
    templateType: 'Tickets',
    description: 'Visualize your data',
  },
  {
    id: '1',
    title: 'Open',
    ticketCount: '0',
    match: 'counter',
    templateType: 'Tickets',
    description: 'Tickets',
  },
  {
    id: '2',
    title: 'Close',
    ticketCount: '12',
    match: 'counter',
    templateType: 'Tickets',
    description: 'Tickets',
  },
  {
    id: '3',
    title: 'Over Due',
    ticketCount: '1',
    match: 'counter',
    templateType: 'Tickets',
    description: 'Tickets',
  },
  {
    id: '4',
    title: 'Unassigned',
    ticketCount: '0',
    match: 'counter',
    templateType: 'Tickets',
    description: 'Tickets',
  },
  {
    id: '5',
    title: 'Resolved',
    ticketCount: '15',
    match: 'counter',
    templateType: 'Tickets',
    description: 'Tickets',
  },
  {
    id: '6',
    title: 'pending',
    ticketCount: '0',
    match: 'counter',
    templateType: 'Tickets',
    description: 'Tickets',
  },
  {
    id: '7',
    title: 'Assets Distribution',
    type: 'Pie Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Tickets',
    subFilter: true,
    match: 'chart',
    templateType: 'Inventory',
    description: 'Visualize your data',
  },
  {
    id: '8',
    title: 'Table',
    tableColumns: ['Name', 'Location', 'Used By', 'Asset life expire on'],
    match: 'table',
    templateType: 'Inventory',
    description: 'General Table',
  },
  {
    id: '9',
    title: 'Total Assets',
    ticketCount: '10',
    match: 'counter',
    templateType: 'Inventory',
    description: 'Inventory Assets',
  },
  {
    id: '10',
    title: 'Hardware',
    ticketCount: '9',
    match: 'counter',
    templateType: 'Inventory',
    description: 'Inventory Assets',
  },
  {
    id: '11',
    title: 'IT Services',
    ticketCount: '8',
    match: 'counter',
    templateType: 'Inventory',
    description: 'Inventory Assets',
  },
  {
    id: '12',
    title: 'Backup Services',
    ticketCount: '7',
    match: 'counter',
    templateType: 'Inventory',
    description: 'Inventory Assets',
  },
  {
    id: '13',
    title: 'Utilizable',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Inventory',
    description: 'Inventory Assets',
  },
  {
    id: '14',
    title: 'Software Distribution',
    type: 'Pie Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Tickets',
    subFilter: true,
    match: 'chart',
    templateType: 'Software',
    description: 'Visualize your data',
  },
  {
    id: '15',
    title: 'Table',
    tableColumns: ['Name', 'Type', 'Managed By', 'Category'],
    match: 'table',
    templateType: 'Software',
    description: 'General Table',
  },
  {
    id: '16',
    title: 'Total Software',
    ticketCount: '0',
    match: 'counter',
    templateType: 'Software',
    description: 'Software Report',
  },
  {
    id: '17',
    title: 'Restricted',
    ticketCount: '10',
    match: 'counter',
    templateType: 'Software',
    description: 'Software Report',
  },
  {
    id: '18',
    title: 'Ignored',
    ticketCount: '9',
    match: 'counter',
    templateType: 'Software',
    description: 'Software Report',
  },
  {
    id: '19',
    title: 'Managed',
    ticketCount: '8',
    match: 'counter',
    templateType: 'Software',
    description: 'Software Report',
  },
  {
    id: '20',
    title: 'Disabled',
    ticketCount: '7',
    match: 'counter',
    templateType: 'Software',
    description: 'Software Report',
  },
  {
    id: '21',
    title: 'InReview',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Software',
    description: 'Software Report',
  },
  {
    id: '22',
    title: 'Contract Distribution',
    type: 'Pie Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Tickets',
    subFilter: true,
    match: 'chart',
    templateType: 'Contract',
    description: 'Visualize your data',
  },
  {
    id: '23',
    title: 'Table',
    tableColumns: ['Name', 'Status', 'Type', 'Expiry Date'],
    match: 'table',
    templateType: 'Contract',
    description: 'General Table',
  },
  {
    id: '24',
    title: 'All',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Contract',
    description: 'Contract',
  },
  {
    id: '25',
    title: 'Lease',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Contract',
    description: 'Contract',
  },
  {
    id: '26',
    title: 'Maintain',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Contract',
    description: 'Contract',
  },
  {
    id: '27',
    title: 'Software',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Contract',
    description: 'Contract',
  },
  {
    id: '28',
    title: 'Warranty',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Contract',
    description: 'Contract',
  },
  {
    id: '29',
    title: 'Purchase Order Distribution',
    type: 'Pie Chart',
    xAxis: 'Task Owner',
    yAxis: 'Status',
    subMetric: 'Tickets',
    subFilter: true,
    match: 'chart',
    templateType: 'Purchase Order',
    description: 'Visualize your data',
  },
  {
    id: '30',
    title: 'Table',
    tableColumns: ['Name', 'Vendor', 'Status', 'Total Cost'],
    match: 'table',
    templateType: 'Purchase Order',
    description: 'General Table',
  },
  {
    id: '31',
    title: 'All',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Purchase Order',
    description: 'Purchase Order',
  },
  {
    id: '32',
    title: 'Approved',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Purchase Order',
    description: 'Purchase Order',
  },
  {
    id: '33',
    title: 'rejected',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Purchase Order',
    description: 'Purchase Order',
  },
  {
    id: '34',
    title: 'Pending',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Purchase Order',
    description: 'Purchase Order',
  },
  {
    id: '35',
    title: 'Received',
    ticketCount: '6',
    match: 'counter',
    templateType: 'Purchase Order',
    description: 'Purchase Order',
  },
];

export const modalInitialState: any = {
  chart: false,
  text: false,
  table: false,
  counter: false,
};

export const servicesMetrics = (setMetricType: any) => [
  {
    title: REPORT_TYPE?.INVENTORIES,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.INVENTORIES);
      closeMenu?.();
    },
  },
  {
    title: REPORT_TYPE?.SOFTWARE,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.SOFTWARE);
      closeMenu?.();
    },
  },
  {
    title: REPORT_TYPE?.CONTRACTS,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.CONTRACTS);
      closeMenu?.();
    },
  },
  {
    title: REPORT_TYPE?.TICKETS,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.TICKETS);
      closeMenu?.();
    },
  },
  {
    title: REPORT_TYPE?.PURCHASE_ORDER,
    handleClick: (closeMenu: any) => {
      setMetricType(REPORT_TYPE?.PURCHASE_ORDER);
      closeMenu?.();
    },
  },
];
