import dynamic from 'next/dynamic';
import { Box, Typography, useTheme, useMediaQuery } from '@mui/material';
import useLeadsReportGraph from './useLeadsReportGraph';
import { styles } from './useLeadsReportGraph.style';

const InvoicesAnalystGraph = () => {
  const theme = useTheme();
  const { series, options } = useLeadsReportGraph();
  const ReactApexChart = dynamic(() => import('react-apexcharts'), {
    ssr: false,
  });

  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  // const responsiveOptions = [
  //   {
  //     breakpoint: 768,
  //     options: {
  //       chart: {
  //         height: isMobile ? 300 : 350,
  //       },
  //     },
  //   },
  // ];

  return (
    <Box sx={styles?.productWiseGraph}>
      <Typography
        sx={{
          color: `${theme?.palette?.custom?.dark_blue}`,
          fontWeight: 600,
          fontSize: '18px',
        }}
      >
        Leads Generated by CTAs
      </Typography>
      <Box
        height={isMobile ? '350px' : '350px'}
        // Add more styles as needed for responsiveness
      >
        <ReactApexChart
          options={{
            ...options,
            chart: {
              ...options.chart,
              // responsive: responsiveOptions,
            },
          }}
          series={series}
          type="bar"
          height={350}
        />
      </Box>
    </Box>
  );
};

export default InvoicesAnalystGraph;
