import {
  TICKET_IMPACT,
  TICKET_PRIORITY,
  TICKET_STATUS,
  TICKET_TYPES,
} from '@/constants/strings';

export const ticketStatusOptions = [
  TICKET_STATUS?.OPEN,
  TICKET_STATUS?.PENDING,
  TICKET_STATUS?.RESOLVED,
  TICKET_STATUS?.CLOSED,
];

export const ticketPriorityOptions = [
  TICKET_PRIORITY?.LOW,
  TICKET_PRIORITY?.MEDIUM,
  TICKET_PRIORITY?.HIGH,
  TICKET_PRIORITY?.URGENT,
];

export const ticketImpactOptions = [
  TICKET_IMPACT?.LOW,
  TICKET_IMPACT?.MEDIUM,
  TICKET_IMPACT?.HIGH,
];

export const ticketSourceOptions = ['Phone', 'Email', 'Portal', 'Chat'];

//TODO: we will use if BE added these.
// export const ticketsTypeOptions = [
//   TICKET_TYPES?.ALL_TICKETS,
//   TICKET_TYPES?.URGENT_AND_HIGH_PRIORITY,
//   TICKET_TYPES?.OPEN_TICKETS_IN_MY_GROUP,
//   TICKET_TYPES?.MY_OVERDUE_TICKETS,
//   TICKET_TYPES?.MY_OPEN_AND_PENDING_TICKETS,
//   TICKET_TYPES?.SPAM_TICKETS,
//   TICKET_TYPES?.NEW_AND_MY_OPEN_TICKETS,
//   TICKET_TYPES?.UNRESOLVED_TICKETS,
//   TICKET_TYPES?.INCIDENTS,
//   TICKET_TYPES?.SERVICE_REQUEST,
//   TICKET_TYPES?.TICKETS_I_REQUESTED,
//   TICKET_TYPES?.SHARED_WITH_ME,
// ];

export const ticketsTypeOptions = [
  TICKET_TYPES?.INCIDENTS,
  TICKET_TYPES?.SERVICE_REQUEST,
];
