export const barChartData = [
  { count: '30', year: '2024', month: '1', status: 'Resolved Tickets' },
  { count: '60', year: '2024', month: '2', status: 'Resolved Tickets' },
  { count: '40', year: '2024', month: '3', status: 'Resolved Tickets' },
  { count: '30', year: '2024', month: '4', status: 'Resolved Tickets' },
  { count: '20', year: '2024', month: '5', status: 'Resolved Tickets' },
  { count: '90', year: '2024', month: '6', status: 'Resolved Tickets' },
  { count: '10', year: '2024', month: '7', status: 'Resolved Tickets' },
  { count: '20', year: '2024', month: '8', status: 'Resolved Tickets' },
  { count: '20', year: '2024', month: '9', status: 'Resolved Tickets' },
  { count: '20', year: '2024', month: '10', status: 'Resolved Tickets' },
  { count: '20', year: '2024', month: '11', status: 'Resolved Tickets' },
  { count: '20', year: '2024', month: '12', status: 'Resolved Tickets' },

  { count: '30', year: '2024', month: '1', status: 'Close Tickets' },
  { count: '70', year: '2024', month: '2', status: 'Close Tickets' },
  { count: '20', year: '2024', month: '3', status: 'Close Tickets' },
  { count: '90', year: '2024', month: '4', status: 'Close Tickets' },
  { count: '40', year: '2024', month: '5', status: 'Close Tickets' },
  { count: '30', year: '2024', month: '6', status: 'Close Tickets' },
  { count: '70', year: '2024', month: '7', status: 'Close Tickets' },
  { count: '50', year: '2024', month: '8', status: 'Close Tickets' },
  { count: '20', year: '2024', month: '9', status: 'Close Tickets' },
  { count: '10', year: '2024', month: '10', status: 'Close Tickets' },
  { count: '80', year: '2024', month: '11', status: 'Close Tickets' },
  { count: '110', year: '2024', month: '12', status: 'Close Tickets' },
];
