export const eventArray = [
  {
    title: 'Testing 1',
    start: '2024-04-10T14:30:00',
    data: {
      email: 'kamran.zafar@ceative.co.uk',
      meetingTitle: 'BA meeting',
      date: 'MON 2/11/23',
      startTime: '11:15 Am',
      endTime: '12:00 Pm',
      invitedBy: 'Waqas Ahmed',
      accepted: '3',
      notResponding: '33',
      listeners: 'Designers',
      attachment: 'HR module division.xlsx',
    },
  },
  {
    title: 'Testing 2',
    start: '2024-04-08T14:30:00',
    data: {
      email: 'ali.raza@ceative.co.uk',
      meetingTitle: 'Demo meeting',
      date: 'MON 2/11/23',
      startTime: '11:15 Am',
      endTime: '12:00 Pm',
      invitedBy: 'Umer Arshed',
      accepted: '3',
      notResponding: '33',
      listeners: 'Designers',
      attachment: 'BA module division.xlsx',
    },
  },
  {
    title: 'Testing 3',
    start: '2024-04-06T14:30:00',
    data: {
      email: 'umer.awan@ceative.co.uk',
      meetingTitle: 'Coordinator meeting',
      date: 'MON 2/11/23',
      startTime: '11:15 Am',
      endTime: '12:00 Pm',
      invitedBy: 'Ali Raza',
      accepted: '3',
      notResponding: '33',
      listeners: 'Managers',
      attachment: 'PM module division.xlsx',
    },
  },
  {
    title: 'Testing 4',
    start: '2024-04-23T14:30:00',
    data: {
      email: 'auns.ali@ceative.co.uk',
      meetingTitle: 'PM meeting',
      date: 'MON 2/11/23',
      startTime: '11:15 Am',
      endTime: '12:00 Pm',
      invitedBy: 'Faisal Naeem',
      accepted: '3',
      notResponding: '33',
      listeners: 'Coordinators',
      attachment: 'BD module division.xlsx',
    },
  },
  {
    title: 'Testing 5',
    start: '2024-04-29T14:30:00',
    data: {
      email: 'ahmer.raza@ceative.co.uk',
      meetingTitle: 'HR meeting',
      date: 'MON 2/11/23',
      startTime: '11:15 Am',
      endTime: '12:00 Pm',
      invitedBy: 'Muhammad Afaq',
      accepted: '3',
      notResponding: '33',
      listeners: 'Developers',
      attachment: 'FE module division.xlsx',
    },
  },
  {
    title: 'Testing 6',
    start: '2024-04-29T10:00:00',
    data: {
      email: 'ali.haider@ceative.co.uk',
      meetingTitle: 'Developer meeting',
      date: 'MON 2/11/23',
      startTime: '11:15 Am',
      endTime: '12:00 Pm',
      invitedBy: 'Ahsan Ali',
      accepted: '3',
      notResponding: '33',
      listeners: 'Management',
      attachment: 'BA module division.xlsx',
    },
  },
];

export const meetingCardArray = (theme: any) => [
  {
    id: 3543,
    heading: 'All',
    meetingsCount: '30',
    color: theme?.palette?.info?.main,
  },
  {
    id: 8476,
    heading: 'Upcoming',
    meetingsCount: '10',
    color: theme?.palette?.error?.main,
  },
  {
    id: 8210,
    heading: 'Completed',
    meetingsCount: '20',
    color: theme?.palette?.success?.dark,
  },
];
