export const assetsFieldsOption = [
  'Name',
  'Asset Type',
  'Location',
  'Used By',
  'Department',
  'Managed By',
  'Impact',
  'End of Life',
  'Created By',
  'Assigned On',
  'Description',
];
export const taskFieldsOption = [
  'Title',
  'Description',
  'Departments',
  'Assign To',
  'Status',
  'Notify Before',
  'Planned Start Date and time',
  'Planned End Date and time',
  'Planned Effort',
  'Select Department',
];
export const ticketsFields = [
  'Select Department',
  'Type',
  'Add Requester',
  'Subject',
  'Source',
  'Status',
  'Priority',
  'Agent',
  'Description',
  'Planned Start Date and Time',
  'Planned End Date and Time',
  'Planned Effort',
];
export const requesterFieldOptions = [
  'Email',
  'Full Name',
  'Job Title',
  'Phone Number',
  'Date of Joining',
];
export const requestedForFieldOptions = [
  'Email',
  'Full Name',
  'Job Title',
  'Phone Number',
  'Date of Joining',
];
export const fieldOptions = [
  'is',
  'is not',
  'equal',
  'not equal',
  'contains',
  'not contains',
  'contains words',
  'not contains words',
  'starts with',
  'ends with',
  'is empty',
  'is not empty',
  'included',
  'not include',
];
export const statusOptions = ['open', 'pending', 'resolved', 'close'];
